--7. 비도서

--DVD더미(30개)(142번부터~)
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 나나나', '도롱뇽', 'DVD', '1994', '디지털자료실', '#!', '장정혜', 'DVDDVD(별치DV)장46ㅇB22', NULL, '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 가가가', '비공서', 'DVD', '1990', '디지털자료실', '#!', '서재순', 'DVDDVD(별치DV)장15ㅇB88', NULL, '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 가가가', '워너브라더스', 'DVD', '2012', '디지털자료실', '#!', '황은영', 'DVDDVD(별치DV)장27ㅇB59', NULL, '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 가가가', '쇼박스', 'DVD', '2013', '디지털자료실', '#!', '양윤현', 'DVDDVD(별치DV)장86ㅇB79', NULL, '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 다다다', '도롱뇽', 'DVD', '2002', '디지털자료실', '#!', '임영', 'DVDDVD(별치DV)장88ㅇB97', NULL, '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 다다다', '비공서', 'DVD', '2013', '디지털자료실', '#!', '오예완', 'DVDDVD(별치DV)장47ㅇB6', NULL, '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 다다다', '쇼박스', 'DVD', '2016', '디지털자료실', '#!', '서혜영', 'DVDDVD(별치DV)장23ㅇB72', NULL, '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 나나나', '알림창', 'DVD', '2002', '디지털자료실', '#!', '고서연', 'DVDDVD(별치DV)장18ㅇB66', NULL, '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 마마마', '쇼박스', 'DVD', '1990', '디지털자료실', '#!', '양새범', 'DVDDVD(별치DV)장39ㅇB60', NULL, '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 다다다', '워너브라더스', 'DVD', '2015', '디지털자료실', '#!', '문도찬', 'DVDDVD(별치DV)장9ㅇB71', NULL, '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 다다다', '도롱뇽', 'DVD', '1992', '디지털자료실', '#!', '전서은', 'DVDDVD(별치DV)장55ㅇB5', NULL, '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 다다다', '도롱뇽', 'DVD', '2009', '디지털자료실', '#!', '한주철', 'DVDDVD(별치DV)장61ㅇB65', NULL, '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 라라라', '워너브라더스', 'DVD', '2014', '디지털자료실', '#!', '최연안', 'DVDDVD(별치DV)장39ㅇB74', NULL, '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 나나나', '쇼박스', 'DVD', '2019', '디지털자료실', '#!', '홍정준', 'DVDDVD(별치DV)장39ㅇB90', NULL, '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 나나나', '워너브라더스', 'DVD', '2000', '디지털자료실', '#!', '문승권', 'DVDDVD(별치DV)장88ㅇB81', NULL, '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 나나나', '쇼박스', 'DVD', '2017', '디지털자료실', '#!', '황시지', 'DVDDVD(별치DV)장13ㅇB80', NULL, '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 다다다', '비공서', 'DVD', '2015', '디지털자료실', '#!', '손새혜', 'DVDDVD(별치DV)장40ㅇB74', NULL, '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 나나나', '도롱뇽', 'DVD', '1996', '디지털자료실', '#!', '오미연', 'DVDDVD(별치DV)장81ㅇB90', NULL, '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 마마마', '도롱뇽', 'DVD', '2010', '디지털자료실', '#!', '남도자', 'DVDDVD(별치DV)장93ㅇB76', NULL, '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 나나나', '쇼박스', 'DVD', '2019', '디지털자료실', '#!', '왕연권', 'DVDDVD(별치DV)장8ㅇB70', NULL, '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 마마마', '도롱뇽', 'DVD', '2019', '디지털자료실', '#!', '권성연', 'DVDDVD(별치DV)장11ㅇB60', NULL, '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 라라라', '워너브라더스', 'DVD', '2015', '디지털자료실', '#!', '유주용', 'DVDDVD(별치DV)장15ㅇB60', NULL, '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 가가가', '비공서', 'DVD', '2004', '디지털자료실', '#!', '이미규', 'DVDDVD(별치DV)장68ㅇB2', NULL, '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 마마마', '알림창', 'DVD', '2013', '디지털자료실', '#!', '홍정성', 'DVDDVD(별치DV)장16ㅇB79', NULL, '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 라라라', '알림창', 'DVD', '2015', '디지털자료실', '#!', '류지지', 'DVDDVD(별치DV)장79ㅇB75', NULL, '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 라라라', '도롱뇽', 'DVD', '1998', '디지털자료실', '#!', '강주혜', 'DVDDVD(별치DV)장34ㅇB6', NULL, '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 나나나', '워너브라더스', 'DVD', '2001', '디지털자료실', '#!', '윤영', 'DVDDVD(별치DV)장39ㅇB66', NULL, '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 가가가', '쇼박스', 'DVD', '2016', '디지털자료실', '#!', '권영혜', 'DVDDVD(별치DV)장36ㅇB55', NULL, '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 나나나', '알림창', 'DVD', '2008', '디지털자료실', '#!', '안승은', 'DVDDVD(별치DV)장40ㅇB66', NULL, '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[DVD] 나나나', '비공서', 'DVD', '2006', '디지털자료실', '#!', '임수은', 'DVDDVD(별치DV)장19ㅇB34', NULL, '예술', '대출가능');


--유효(도곡정보문화도서관 참고)
--CD (23개)
SET DEFINE OFF;
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Debussy 영상, 어린이 차지, 베르가마스크 모음곡, 기쁨의 섬 - 조성진]', '유니버설뮤직코리아 [제작]', 'CD', '1997', '디지털자료실', '#!', 'Seong-jin Cho', 'CD 676-조54ㄷ', '8808678123517', '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] 두번째 달', '스톤뮤직엔터테인먼트 [제작]', 'CD', '1993', '디지털자료실', '#!', '두번째달', 'CD 673.511-두44ㄷ', '8809231383331', '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] 지금 나오는 곡이 뭐예요? Piano solo 40', '소니뮤직코리아 [제작]', 'CD', '1997', '디지털자료실', '#!', '소니뮤직 [제작]', 'CD 676-소198ㅈ', '8803581181081', '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] European fantasy', '워너뮤직코리아 [제작]', 'CD', '2015', '디지털자료실', '#!', 'Yoonhan', 'CD 676-윤92ㅇ', '8809355976082', '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] (The)Wanderer schubert, berg, liszt: 방랑자 환상곡 & 베르크, 리스트 : 피아노 소나타', '유니버설뮤직코리아 [제작]', 'CD', '2016', '디지털자료실', '#!', '조성진 연주', 'CD 676-조54ㅇ', '8808678124064', '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] (The)Best Reminiscent: 10th anniversary', '소니뮤직코리아 [제작]', 'CD', '2000', '디지털자료실', '#!', 'Yiruma', 'CD 676-이296ㅂ', '8803581194005', '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Moment', '뮤직앤뉴 [제작]', 'CD', '2019', '디지털자료실', '#!', 'Standing Egg', 'CD 676-스883ㅁ', '8809447084145', '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Romance collection: 10th anniversary', '씨앤엘뮤직', 'CD', '1995', '디지털자료실', '#!', 'Yuhki Kuramoto [작곡]', 'CD 676-유878ㄹ', '8806344801417', '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Harry Potter and the chamber of secrets. 2-1 - 2-8', 'Random House Publishing', 'CD', '2015', '디지털자료실', '#!', 'J.K. Rowling ; performance by Jim Dalf', 'CD 843-R884h-v.2-7', '0807281948', '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Harry Potter and the sorcerer''s stone. 1-1 - 1-7', 'Random House Publishing', 'CD', '1993', '디지털자료실', '#!', 'J.K. Rowling ; performance by Jim Dalf', 'CD 843-R884h-v.1-1', '9780807281956', '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Harry Potter and the sorcerer''s stone. 1-1 - 1-7', 'Random House Publishing', 'CD', '1999', '디지털자료실', '#!', 'J.K. Rowling ; performance by Jim Dalf', 'CD 843-R884h-v.1-3', '9780807281956', '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Harry Potter and the sorcerer''s stone. 1-1 - 1-7', 'Random House Publishing', 'CD', '2012', '디지털자료실', '#!', 'J.K. Rowling ; performance by Jim Dalf', 'CD 843-R884h-v.1-5', '9780807281956', '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Harry Potter and the sorcerer''s stone. 1-1 - 1-7', 'Random House Publishing', 'CD', '1997', '디지털자료실', '#!', 'J.K. Rowling ; performance by Jim Dalf', 'CD 843-R884h-v.1-7', '9780807281956', '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Harry Potter and the chamber of secrets. 2-1 - 2-8', 'Random House Publishing', 'CD', '2007', '디지털자료실', '#!', 'J.K. Rowling ; performance by Jim Dalf', 'CD 843-R884h-v.2-2', '0807281948', '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Harry Potter and the chamber of secrets. 2-1 - 2-8', 'Random House Publishing', 'CD', '1999', '디지털자료실', '#!', 'J.K. Rowling ; performance by Jim Dalf', 'CD 843-R884h-v.2-4', '0807281948', '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Harry Potter and the sorcerer''s stone. 1-1 - 1-7', 'Random House Publishing', 'CD', '2015', '디지털자료실', '#!', 'J.K. Rowling ; performance by Jim Dalf', 'CD 843-R884h-v.1-2', '9780807281956', '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Harry Potter and the sorcerer''s stone. 1-1 - 1-7', 'Random House Publishing', 'CD', '1993', '디지털자료실', '#!', 'J.K. Rowling ; performance by Jim Dalf', 'CD 843-R884h-v.1-4', '9780807281956', '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Harry Potter and the sorcerer''s stone. 1-1 - 1-7', 'Random House Publishing', 'CD', '1996', '디지털자료실', '#!', 'J.K. Rowling ; performance by Jim Dalf', 'CD 843-R884h-v.1-6', '9780807281956', '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Harry Potter and the chamber of secrets. 2-1 - 2-8', 'Random House Publishing', 'CD', '2003', '디지털자료실', '#!', 'J.K. Rowling ; performance by Jim Dalf', 'CD 843-R884h-v.2-1', '0807281948', '예술', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Harry Potter and the chamber of secrets. 2-1 - 2-8', 'Random House Publishing', 'CD', '2015', '디지털자료실', '#!', 'J.K. Rowling ; performance by Jim Dalf', 'CD 843-R884h-v.2-3', '0807281948', '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Harry Potter and the chamber of secrets. 2-1 - 2-8', 'Random House Publishing', 'CD', '1994', '디지털자료실', '#!', 'J.K. Rowling ; performance by Jim Dalf', 'CD 843-R884h-v.2-5', '0807281948', '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Harry Potter and the chamber of secrets. 2-1 - 2-8', 'Random House Publishing', 'CD', '2002', '디지털자료실', '#!', 'J.K. Rowling ; performance by Jim Dalf', 'CD 843-R884h-v.2-6', '0807281948', '예술', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[CD] Harry Potter and the chamber of secrets. 2-1 - 2-8', 'Random House Publishing', 'CD', '2011', '디지털자료실', '#!', 'J.K. Rowling ; performance by Jim Dalf', 'CD 843-R884h-v.2-8', '0807281948', '예술', '대출가능');


--유효(강동구립도서관 참고)
--eBOOK (30개, ISBN유효 10개)
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 맹자 : 이익에 반대한 경세가', '살림출판사', 'eBook', '2013', '디지털자료실', '#!', '장현근', 'EB 340.1-ㅈ222ㅁ', '9788952227164', '언어', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 창백한 불꽃 : 블라디미르 나보코프 장편소설', '문학동네', 'eBook', '2019', '디지털자료실', '#!', '블라디미르 나보코프', 'EB 843-ㄴ27ㅊ', '9788954655200', '철학종교', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 붉은 웃음', '위즈덤커넥트 :Wisdom Connect', 'eBook', '2019', '디지털자료실', '#!', '레오니드 안드레예프', 'EB 892.83-ㅇ199ㅂ', '9788964065297 ', '철학종교', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 유괴', '엘릭시르 :문학동네', 'eBook', '2014', '디지털자료실', '#!', '다카기 아키미쓰', 'EB 833.6-ㄷ46ㅇ', '9788989354895', '철학종교', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 철의 시대 : J.M. 쿳시 장편소설', '문학동네', 'eBook', '2019', '디지털자료실', '#!', 'J.M. 쿳시', 'EB 843.5-ㅋ778ㅊ', '9788975274169', '철학종교', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 근대 장애인사 : 장애인 소외와 배제의 기원을 찾아서', '사우', 'eBook', '2019', '디지털자료실', '#!', '정창권', 'EB 338.30911-ㅈ494ㄱ', '9796871621808', '철학종교', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 그 페미니즘이 당신을 불행하게 하는 이유 : 그들이 말하지 않는 진실', '리얼뉴스', 'eBook', '2019', '디지털자료실', '#!', '오세라비', 'EB 337.2-ㅇ389ㄱ', '9791196649104', '철학종교', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 습관을 바꾸는 생각의 힘 : 무의식적으로 생긴 습관을 의식적으로 바꾸는 변화의 기술', '이터', 'eBook', '2020', '디지털자료실', '#!', '야마사키 히로시', 'EB 325.211-ㅇ264ㅅ', 
'9791189436209', '사회과학', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 대사치료 암을 굶겨 죽이다 : 케톤 식이와 심층영양 개인 맞춤 치료의 통합', '처음북스', 'eBook', '2018', '디지털자료실', '#!', '나샤 윈터스,제스 히긴스 켈리', 'EB 513.994-ㅇ561ㄷ', 
'9791170221579', '사회과학', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 엄마가 모르는 초등 3학년 교실 : 공부 습관이 길러지고 사회성이 자라는 교실 생활 들여다보기', '평사리', 'eBook', '2013', '디지털자료실', '#!', '박관수', 'EB 375.3-ㅂ184ㅇ', 
'9788992241465', '사회과학', '대출불가');
--더미
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 너무 시끄러운 고독 : 보후밀 흐라발 장편소설', '문학동네', 'eBook', '2016', '디지털자료실', '#!', '보후밀 흐라발', 'EB 892.96-ㅎ955ㄴ', '9797070168073', '사회과학', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 물질의 탐구 : 그리스 원자로부터 상대성이론, 양자역학에 이르기까지 질량과 물질을 이해하기 위한 길고 긴 여정', '반니', 'eBook', '2018', '디지털자료실', '#!', '짐 배것', 'EB 420.163-ㅂ656ㅁ', '9791751592609', '사회과학', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 진화한 마음 : 전중환의 본격 진화심리학', 'Humanist :휴머니스트 출판그룹', 'eBook', '2019', '디지털자료실', '#!', '전중환', 'EB 182.4-ㅈ322ㅈ', '9792943037669', '사회과학', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 블랙홀과 시간여행 : 아인슈타인의 찬란한 유산', '반니', 'eBook', '2019', '디지털자료실', '#!', '킵 S. 손', 'EB 420.12-ㅅ496ㅂ', '9792722342611', '사회과학', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] (켄 피셔) 역발상 주식 투자', '한국경제신문 :한경BP', 'eBook', '2017', '디지털자료실', '#!', '켄 피셔,엘리자베스 델린저', 'EB 327.856-ㅍ85ㅇ', '9799024719692', '사회과학', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 나는 어떻게 시장을 이겼나 : 월가를 정복한 수학자 퀀트투자의 아버지 에드워드 소프', '이레미디어', 'eBook', '2019', '디지털자료실', '#!', '에드워드 O. 소프', 'EB 327.856-ㅅ434ㄴ', '9798234735045', '사회과학', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 금리는 주식시장의 미래를 알고 있다 : 금리인상기에 현명한 투자자가 되는 방법', '메이트북스 :원앤원콘텐츠그룹', 'eBook', '2018', '디지털자료실', '#!', '정웅지', 'EB 327.856-ㅈ452ㄱ', '9795003370317', '사회과학', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 정해진 미래 시장의 기회 : 인구변동에서 기회를 발굴하는 미래예측법', '북스톤', 'eBook', '2018', '디지털자료실', '#!', '조영태', 'EB 331.544-ㅈ648ㅈ', '9792338571785', '사회과학', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 상품선물 추세탐지하는법 : 주식투자와 상품선물옵션 시장의 흐름을 이해하는 시작', 'Grenoble', 'eBook', '2018', '디지털자료실', '#!', '윌리엄 D. 갠', 'EB 327.86-ㄱ271ㅅ', '9796099065766', '사회과학', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 매우 예민한 사람들을 위한 책 : 뇌과학과 정신의학이 들려주는 당신 마음에 대한 이야기', '글항아리', 'eBook', '2020', '디지털자료실', '#!', '전홍진', 'EB 186.3-ㅈ334ㅁ', '9796423532028', '자연과학', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 삼민주의', '범우사', 'eBook', '2000', '디지털자료실', '#!', '쑨원', 'EB 340.2-ㅅ998ㅅ', '9793768934389', '자연과학', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 작은 별이지만 빛나고 있어 : 소윤 에세이', '북로망스', 'eBook', '2021', '디지털자료실', '#!', '소윤', 'EB 818-ㅅ432ㅈ', '9795706412101', '자연과학', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 불편한 편의점 : 김호연 장편소설', '나무옆의자', 'eBook', '2021', '디지털자료실', '#!', '김호연', 'EB 813.7-ㄱ989ㅂ', '9796200780443', '문학', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 소크라테스 익스프레스 : 철학이 우리 인생에 스며드는 순간', '어크로스출판그룹', 'eBook', '2021', '디지털자료실', '#!', '에릭 와이너', 'EB 160-ㅇ483ㅅ', '9797580394086', '문학', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] (중·고등 내신과 입시를 결정짓는) 초3 수학의 힘', '물주는아이 :백도씨', 'eBook', '2021', '디지털자료실', '#!', '이정', 'EB 375.441-ㅇ866ㅊ', '9798971144175', '문학', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 초3부터 진로 코칭 : 유튜브 시대, 어떻게 내 아이의 경쟁력을 갖출까?', '넥서스', 'eBook', '2020', '디지털자료실', '#!', '김기영', 'EB 375.2268-ㄱ681ㅊ', '9792313650684', '문학', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 3번 읽기의 힘 : 책 읽기로 인생을 바꾼 베스트셀러 작가의 반복 독서법', '반니', 'eBook', '2021', '디지털자료실', '#!', '김범준', 'EB 029.4-ㄱ738ㅅ', '9792884796528', '문학', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 일인칭 단수 : 무라카미 하루키 소설', '문학동네', 'eBook', '2020', '디지털자료실', '#!', '무라카미 하루키', 'EB 833.6-ㅁ666ㅇ', '9798000612221', '문학', '대출불가');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 명상록', '현대지성', 'eBook', '2018', '디지털자료실', '#!', '마르쿠스 아우렐리우스', 'EB 160.258-ㅁ144ㅁ', '9791959174136', '철학', '대출가능');
insert into tblNonBook (nbook_seq, nbook_subject, nbook_publisher, nbook_kind, nbook_date, nbook_position, nbook_image, nbook_author, nbook_callnumber, nbook_isbn, nbook_genre, nbook_status) values (seqNonBook.nextVal, '[eBook] 우연 제작자들', '푸른숲', 'eBook', '2020', '디지털자료실', '#!', '요아브 블럼', 'EB 897.4-ㅂ962ㅇ', '9796804654492', '문학', '대출불가');



COMMIT;










