
insert into tblReview values (seqReview.nextval,4,40,'개인적으로 완전 만족하면서 봤음 강추bb',1);
insert into tblReview values (seqReview.nextval,4,40,'고전의 힘',2);
insert into tblReview values (seqReview.nextval,1,80,'재밌어요',3);
insert into tblReview values (seqReview.nextval,3,40,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',4);
insert into tblReview values (seqReview.nextval,2,60,'저는 약간 지루했네요;;',5);
insert into tblReview values (seqReview.nextval,2,60,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',6);
insert into tblReview values (seqReview.nextval,2,100,'재밌어요',7);
insert into tblReview values (seqReview.nextval,1,100,'보는내내 답답합니다.정말 답답합니다.',8);
insert into tblReview values (seqReview.nextval,1,60,'손에 꼽히는 인생캐릭터를 만난 것 같다',9);
insert into tblReview values (seqReview.nextval,4,40,'생각보다 유치했어요',10);
insert into tblReview values (seqReview.nextval,5,20,'몰입도 짱짱ㅜㅜ',11);
insert into tblReview values (seqReview.nextval,3,100,'This film is dedicated to our kids. Please don’t grow up. Ever',12);
insert into tblReview values (seqReview.nextval,1,40,'3번을 보아도 시간가는 줄 몰랐습니다',13);
insert into tblReview values (seqReview.nextval,2,60,'슬픔이 있어야 행복이 존재한다.',14);
insert into tblReview values (seqReview.nextval,4,80,'보는내내 답답합니다.정말 답답합니다.',15);
insert into tblReview values (seqReview.nextval,1,20,'3번을 보아도 시간가는 줄 몰랐습니다',16);
insert into tblReview values (seqReview.nextval,3,20,'너무좋았습니다 주옥같은 대사들의 향연',17);
insert into tblReview values (seqReview.nextval,3,20,'몰입도 짱짱ㅜㅜ',18);
insert into tblReview values (seqReview.nextval,1,40,'길을 잃어야 길을 찾는법을 안다',19);
insert into tblReview values (seqReview.nextval,3,60,'재밌었어요 재미있게 봤습니당',20);
insert into tblReview values (seqReview.nextval,5,20,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',21);
insert into tblReview values (seqReview.nextval,1,80,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',22);
insert into tblReview values (seqReview.nextval,1,40,'길을 잃어야 길을 찾는법을 안다',23);
insert into tblReview values (seqReview.nextval,2,20,'동화같은화면 동화같은이야기',24);
insert into tblReview values (seqReview.nextval,4,80,'언제 봐도 좋습니다 ~~!^^',25);
insert into tblReview values (seqReview.nextval,3,80,'3번을 보아도 시간가는 줄 몰랐습니다',26);
insert into tblReview values (seqReview.nextval,2,80,'재미있다. 아름답다. 예쁘다.',27);
insert into tblReview values (seqReview.nextval,2,80,'이 시리지는 다 봐야겠음.',28);
insert into tblReview values (seqReview.nextval,4,80,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',29);
insert into tblReview values (seqReview.nextval,4,60,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',30);
insert into tblReview values (seqReview.nextval,4,80,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',31);
insert into tblReview values (seqReview.nextval,5,20,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',32);
insert into tblReview values (seqReview.nextval,4,40,'저는 약간 지루했네요;;',33);
insert into tblReview values (seqReview.nextval,2,20,'This film is dedicated to our kids. Please don’t grow up. Ever',34);
insert into tblReview values (seqReview.nextval,3,100,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',35);
insert into tblReview values (seqReview.nextval,3,80,'동심으로 떠나는 여행...? 좀 부족하다...',36);
insert into tblReview values (seqReview.nextval,3,40,'기대이상으로 너무 재밌어요',37);
insert into tblReview values (seqReview.nextval,4,100,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',38);
insert into tblReview values (seqReview.nextval,4,100,'너무좋았습니다 주옥같은 대사들의 향연',39);
insert into tblReview values (seqReview.nextval,3,20,'언제 봐도 좋습니다 ~~!^^',40);
insert into tblReview values (seqReview.nextval,4,60,'슬픔이 있어야 행복이 존재한다.',41);
insert into tblReview values (seqReview.nextval,5,40,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',42);
insert into tblReview values (seqReview.nextval,5,100,'생각보다 유치했어요',43);
insert into tblReview values (seqReview.nextval,1,40,'생각보다 유치했어요',44);
insert into tblReview values (seqReview.nextval,2,20,'기대이상으로 너무 재밌어요',45);
insert into tblReview values (seqReview.nextval,4,60,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',46);
insert into tblReview values (seqReview.nextval,2,20,'너무좋았습니다 주옥같은 대사들의 향연',47);
insert into tblReview values (seqReview.nextval,5,80,'고전의 힘',48);
insert into tblReview values (seqReview.nextval,1,40,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',49);
insert into tblReview values (seqReview.nextval,1,80,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',50);
insert into tblReview values (seqReview.nextval,4,60,'생각보다 유치했어요',51);
insert into tblReview values (seqReview.nextval,3,20,'슬픔이 있어야 행복이 존재한다.',52);
insert into tblReview values (seqReview.nextval,3,80,'슬픔이 있어야 행복이 존재한다.',53);
insert into tblReview values (seqReview.nextval,2,40,'개인적으로 완전 만족하면서 봤음 강추bb',54);
insert into tblReview values (seqReview.nextval,4,60,'생각보다 유치했어요',55);
insert into tblReview values (seqReview.nextval,3,20,'감동적입니다.',56);
insert into tblReview values (seqReview.nextval,5,20,'청춘이란 이유로 용기낼 수 있는 해가 뜨기 전 하룻밤까지만',57);
insert into tblReview values (seqReview.nextval,4,100,'왜 평점이 높은지 모르겠음',58);
insert into tblReview values (seqReview.nextval,4,80,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',59);
insert into tblReview values (seqReview.nextval,3,20,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',60);
insert into tblReview values (seqReview.nextval,4,40,'꿀잼',61);
insert into tblReview values (seqReview.nextval,4,60,'길을 잃어야 길을 찾는법을 안다',62);
insert into tblReview values (seqReview.nextval,1,20,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',63);
insert into tblReview values (seqReview.nextval,5,60,'재밌어요',64);
insert into tblReview values (seqReview.nextval,4,100,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',65);
insert into tblReview values (seqReview.nextval,2,60,'꿀잼',66);
insert into tblReview values (seqReview.nextval,4,60,'슬픔이 있어야 행복이 존재한다.',67);
insert into tblReview values (seqReview.nextval,5,100,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',68);
insert into tblReview values (seqReview.nextval,3,100,'동심으로 떠나는 여행...? 좀 부족하다...',69);
insert into tblReview values (seqReview.nextval,1,20,'동화같은화면 동화같은이야기',70);
insert into tblReview values (seqReview.nextval,1,20,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',71);
insert into tblReview values (seqReview.nextval,5,20,'청춘이란 이유로 용기낼 수 있는 해가 뜨기 전 하룻밤까지만',72);
insert into tblReview values (seqReview.nextval,5,100,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',73);
insert into tblReview values (seqReview.nextval,1,80,'저는 약간 지루했네요;;',74);
insert into tblReview values (seqReview.nextval,5,100,'3번을 보아도 시간가는 줄 몰랐습니다',75);
insert into tblReview values (seqReview.nextval,5,60,'청춘이란 이유로 용기낼 수 있는 해가 뜨기 전 하룻밤까지만',76);
insert into tblReview values (seqReview.nextval,4,100,'손에 꼽히는 인생캐릭터를 만난 것 같다',77);
insert into tblReview values (seqReview.nextval,4,60,'고전의 힘',78);
insert into tblReview values (seqReview.nextval,4,60,'재밌어요',79);
insert into tblReview values (seqReview.nextval,3,40,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',80);
insert into tblReview values (seqReview.nextval,2,80,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',81);
insert into tblReview values (seqReview.nextval,1,40,'위로를 주는 존재와 목소리',82);
insert into tblReview values (seqReview.nextval,3,20,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',83);
insert into tblReview values (seqReview.nextval,5,60,'재밌어요',84);
insert into tblReview values (seqReview.nextval,4,80,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',85);
insert into tblReview values (seqReview.nextval,4,80,'재밌었어요 재미있게 봤습니당',86);
insert into tblReview values (seqReview.nextval,4,40,'감동적입니다.',87);
insert into tblReview values (seqReview.nextval,3,20,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',88);
insert into tblReview values (seqReview.nextval,4,80,'재미있다. 아름답다. 예쁘다.',89);
insert into tblReview values (seqReview.nextval,1,40,'개인적으로 완전 만족하면서 봤음 강추bb',90);
insert into tblReview values (seqReview.nextval,3,80,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',91);
insert into tblReview values (seqReview.nextval,3,40,'위로를 주는 존재와 목소리',92);
insert into tblReview values (seqReview.nextval,2,60,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',93);
insert into tblReview values (seqReview.nextval,5,60,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',94);
insert into tblReview values (seqReview.nextval,4,80,'사랑하는 사람과 함께라면 어디든 낙원이다.',95);
insert into tblReview values (seqReview.nextval,4,60,'몰입도 짱짱ㅜㅜ',96);
insert into tblReview values (seqReview.nextval,1,100,'몰입도 짱짱ㅜㅜ',97);
insert into tblReview values (seqReview.nextval,5,80,'한 소년과 한 소녀 그리고 그들만의 판타지',98);
insert into tblReview values (seqReview.nextval,4,40,'이 시리지는 다 봐야겠음.',99);
insert into tblReview values (seqReview.nextval,4,100,'모르겠다. 그냥 펑펑 울었다..',100);
insert into tblReview values (seqReview.nextval,2,100,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',101);
insert into tblReview values (seqReview.nextval,4,20,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',102);
insert into tblReview values (seqReview.nextval,4,60,'고전의 힘',103);
insert into tblReview values (seqReview.nextval,5,100,'3번을 보아도 시간가는 줄 몰랐습니다',104);
insert into tblReview values (seqReview.nextval,5,40,'우리는 매일매일 행복한 연대를',105);
insert into tblReview values (seqReview.nextval,2,20,'사랑하는 사람과 함께라면 어디든 낙원이다.',106);
insert into tblReview values (seqReview.nextval,1,80,'생각보다 유치했어요',107);
insert into tblReview values (seqReview.nextval,1,100,'This film is dedicated to our kids. Please don’t grow up. Ever',108);
insert into tblReview values (seqReview.nextval,2,40,'이 시리지는 다 봐야겠음.',109);
insert into tblReview values (seqReview.nextval,1,60,'최근본거중에 레전드ㄷㄷ',110);
insert into tblReview values (seqReview.nextval,1,60,'감동적입니다.',111);
insert into tblReview values (seqReview.nextval,2,80,'감동적입니다.',112);
insert into tblReview values (seqReview.nextval,2,40,'언제 봐도 좋습니다 ~~!^^',113);
insert into tblReview values (seqReview.nextval,1,60,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',114);
insert into tblReview values (seqReview.nextval,1,60,'모르겠다. 그냥 펑펑 울었다..',115);
insert into tblReview values (seqReview.nextval,3,60,'동심으로 떠나는 여행...? 좀 부족하다...',116);
insert into tblReview values (seqReview.nextval,3,60,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',117);
insert into tblReview values (seqReview.nextval,4,20,'동화같은화면 동화같은이야기',118);
insert into tblReview values (seqReview.nextval,2,80,'길을 잃어야 길을 찾는법을 안다',119);
insert into tblReview values (seqReview.nextval,4,60,'우리는 매일매일 행복한 연대를',120);
insert into tblReview values (seqReview.nextval,4,60,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',121);
insert into tblReview values (seqReview.nextval,5,20,'모르겠다. 그냥 펑펑 울었다..',122);
insert into tblReview values (seqReview.nextval,2,40,'사랑하는 사람과 함께라면 어디든 낙원이다.',123);
insert into tblReview values (seqReview.nextval,1,80,'재밌어요',124);
insert into tblReview values (seqReview.nextval,1,80,'몰입도 짱짱ㅜㅜ',125);
insert into tblReview values (seqReview.nextval,4,100,'청춘이란 이유로 용기낼 수 있는 해가 뜨기 전 하룻밤까지만',126);
insert into tblReview values (seqReview.nextval,1,60,'사랑하는 사람과 함께라면 어디든 낙원이다.',127);
insert into tblReview values (seqReview.nextval,4,20,'사랑하는 사람과 함께라면 어디든 낙원이다.',128);
insert into tblReview values (seqReview.nextval,3,40,'이 시리지는 다 봐야겠음.',129);
insert into tblReview values (seqReview.nextval,2,60,'This film is dedicated to our kids. Please don’t grow up. Ever',130);
insert into tblReview values (seqReview.nextval,2,60,'우리는 매일매일 행복한 연대를',131);
insert into tblReview values (seqReview.nextval,5,60,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',132);
insert into tblReview values (seqReview.nextval,4,100,'길을 잃어야 길을 찾는법을 안다',133);
insert into tblReview values (seqReview.nextval,3,80,'꿀잼',134);
insert into tblReview values (seqReview.nextval,5,100,'This film is dedicated to our kids. Please don’t grow up. Ever',135);
insert into tblReview values (seqReview.nextval,3,80,'동화같은화면 동화같은이야기',136);
insert into tblReview values (seqReview.nextval,5,40,'웨스앤더슨의 동화속에서 살고싶다.',137);
insert into tblReview values (seqReview.nextval,4,100,'너무좋았습니다 주옥같은 대사들의 향연',138);
insert into tblReview values (seqReview.nextval,3,100,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',139);
insert into tblReview values (seqReview.nextval,1,40,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',140);
insert into tblReview values (seqReview.nextval,4,100,'고전의 힘',141);
insert into tblReview values (seqReview.nextval,3,60,'동심으로 떠나는 여행...? 좀 부족하다...',142);
insert into tblReview values (seqReview.nextval,3,60,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',143);
insert into tblReview values (seqReview.nextval,3,20,'보는내내 답답합니다.정말 답답합니다.',144);
insert into tblReview values (seqReview.nextval,3,80,'너무좋았습니다 주옥같은 대사들의 향연',145);
insert into tblReview values (seqReview.nextval,5,80,'재미있다. 아름답다. 예쁘다.',146);
insert into tblReview values (seqReview.nextval,2,20,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',147);
insert into tblReview values (seqReview.nextval,3,100,'모르겠다. 그냥 펑펑 울었다..',148);
insert into tblReview values (seqReview.nextval,4,80,'감정을 억제하기보다 보듬어야 하는 이유.',149);
insert into tblReview values (seqReview.nextval,4,100,'왜 평점이 높은지 모르겠음',150);
insert into tblReview values (seqReview.nextval,3,60,'재밌어요',151);
insert into tblReview values (seqReview.nextval,1,40,'이 시리지는 다 봐야겠음.',152);
insert into tblReview values (seqReview.nextval,3,40,'꿀잼',153);
insert into tblReview values (seqReview.nextval,2,100,'이 시리지는 다 봐야겠음.',154);
insert into tblReview values (seqReview.nextval,3,20,'슬픔이 있어야 행복이 존재한다.',155);
insert into tblReview values (seqReview.nextval,5,40,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',156);
insert into tblReview values (seqReview.nextval,5,40,'꿀잼',157);
insert into tblReview values (seqReview.nextval,4,100,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',158);
insert into tblReview values (seqReview.nextval,1,60,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',159);
insert into tblReview values (seqReview.nextval,4,40,'감정을 억제하기보다 보듬어야 하는 이유.',160);
insert into tblReview values (seqReview.nextval,5,100,'웨스앤더슨의 동화속에서 살고싶다.',161);
insert into tblReview values (seqReview.nextval,1,40,'생각보다 유치했어요',162);
insert into tblReview values (seqReview.nextval,3,60,'사랑하는 사람과 함께라면 어디든 낙원이다.',163);
insert into tblReview values (seqReview.nextval,3,40,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',164);
insert into tblReview values (seqReview.nextval,4,100,'위로를 주는 존재와 목소리',165);
insert into tblReview values (seqReview.nextval,2,100,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',166);
insert into tblReview values (seqReview.nextval,4,20,'감동적입니다.',167);
insert into tblReview values (seqReview.nextval,2,100,'재미있다. 아름답다. 예쁘다.',168);
insert into tblReview values (seqReview.nextval,2,60,'이 시리지는 다 봐야겠음.',169);
insert into tblReview values (seqReview.nextval,3,20,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',170);
insert into tblReview values (seqReview.nextval,4,20,'언제 봐도 좋습니다 ~~!^^',171);
insert into tblReview values (seqReview.nextval,4,40,'길을 잃어야 길을 찾는법을 안다',172);
insert into tblReview values (seqReview.nextval,5,60,'손에 꼽히는 인생캐릭터를 만난 것 같다',173);
insert into tblReview values (seqReview.nextval,2,100,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',174);
insert into tblReview values (seqReview.nextval,3,60,'재미있다. 아름답다. 예쁘다.',175);
insert into tblReview values (seqReview.nextval,5,40,'개인적으로 완전 만족하면서 봤음 강추bb',176);
insert into tblReview values (seqReview.nextval,4,100,'너무좋았습니다 주옥같은 대사들의 향연',177);
insert into tblReview values (seqReview.nextval,5,100,'청춘이란 이유로 용기낼 수 있는 해가 뜨기 전 하룻밤까지만',178);
insert into tblReview values (seqReview.nextval,1,100,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',179);
insert into tblReview values (seqReview.nextval,5,20,'길을 잃어야 길을 찾는법을 안다',180);
insert into tblReview values (seqReview.nextval,4,80,'꿀잼',181);
insert into tblReview values (seqReview.nextval,1,80,'웨스앤더슨의 동화속에서 살고싶다.',182);
insert into tblReview values (seqReview.nextval,4,20,'사랑하는 사람과 함께라면 어디든 낙원이다.',183);
insert into tblReview values (seqReview.nextval,1,100,'한 소년과 한 소녀 그리고 그들만의 판타지',184);
insert into tblReview values (seqReview.nextval,1,40,'위로를 주는 존재와 목소리',185);
insert into tblReview values (seqReview.nextval,5,80,'저는 약간 지루했네요;;',186);
insert into tblReview values (seqReview.nextval,4,80,'감정을 억제하기보다 보듬어야 하는 이유.',187);
insert into tblReview values (seqReview.nextval,3,60,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',188);
insert into tblReview values (seqReview.nextval,5,80,'언제 봐도 좋습니다 ~~!^^',189);
insert into tblReview values (seqReview.nextval,4,60,'고전의 힘',190);
insert into tblReview values (seqReview.nextval,5,20,'언제 봐도 좋습니다 ~~!^^',191);
insert into tblReview values (seqReview.nextval,3,80,'왜 평점이 높은지 모르겠음',192);
insert into tblReview values (seqReview.nextval,3,40,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',193);
insert into tblReview values (seqReview.nextval,5,80,'This film is dedicated to our kids. Please don’t grow up. Ever',194);
insert into tblReview values (seqReview.nextval,4,100,'별 다섯개를 오색으로 입히고 싶다.',195);
insert into tblReview values (seqReview.nextval,4,100,'별 다섯개를 오색으로 입히고 싶다.',196);
insert into tblReview values (seqReview.nextval,5,60,'왜 평점이 높은지 모르겠음',197);
insert into tblReview values (seqReview.nextval,5,20,'This film is dedicated to our kids. Please don’t grow up. Ever',198);
insert into tblReview values (seqReview.nextval,1,40,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',199);
insert into tblReview values (seqReview.nextval,5,80,'사랑하는 사람과 함께라면 어디든 낙원이다.',200);
insert into tblReview values (seqReview.nextval,2,80,'청춘이란 이유로 용기낼 수 있는 해가 뜨기 전 하룻밤까지만',201);
insert into tblReview values (seqReview.nextval,3,40,'왜 평점이 높은지 모르겠음',202);
insert into tblReview values (seqReview.nextval,4,60,'왜 평점이 높은지 모르겠음',203);
insert into tblReview values (seqReview.nextval,2,60,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',204);
insert into tblReview values (seqReview.nextval,1,100,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',205);
insert into tblReview values (seqReview.nextval,4,20,'개인적으로 완전 만족하면서 봤음 강추bb',206);
insert into tblReview values (seqReview.nextval,2,20,'웨스앤더슨의 동화속에서 살고싶다.',207);
insert into tblReview values (seqReview.nextval,3,80,'저는 약간 지루했네요;;',208);
insert into tblReview values (seqReview.nextval,1,60,'동화같은화면 동화같은이야기',209);
insert into tblReview values (seqReview.nextval,5,60,'최근본거중에 레전드ㄷㄷ',210);
insert into tblReview values (seqReview.nextval,4,60,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',211);
insert into tblReview values (seqReview.nextval,1,80,'최근본거중에 레전드ㄷㄷ',212);
insert into tblReview values (seqReview.nextval,1,20,'손에 꼽히는 인생캐릭터를 만난 것 같다',213);
insert into tblReview values (seqReview.nextval,5,100,'너무좋았습니다 주옥같은 대사들의 향연',214);
insert into tblReview values (seqReview.nextval,4,20,'한 소년과 한 소녀 그리고 그들만의 판타지',215);
insert into tblReview values (seqReview.nextval,5,40,'너무좋았습니다 주옥같은 대사들의 향연',216);
insert into tblReview values (seqReview.nextval,4,40,'최근본거중에 레전드ㄷㄷ',217);
insert into tblReview values (seqReview.nextval,5,40,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',218);
insert into tblReview values (seqReview.nextval,5,60,'우리는 매일매일 행복한 연대를',219);
insert into tblReview values (seqReview.nextval,2,60,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',220);
insert into tblReview values (seqReview.nextval,5,80,'재미있다. 아름답다. 예쁘다.',221);
insert into tblReview values (seqReview.nextval,3,40,'고전의 힘',222);
insert into tblReview values (seqReview.nextval,1,40,'3번을 보아도 시간가는 줄 몰랐습니다',223);
insert into tblReview values (seqReview.nextval,4,80,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',224);
insert into tblReview values (seqReview.nextval,4,100,'고전의 힘',225);
insert into tblReview values (seqReview.nextval,3,80,'동화같은화면 동화같은이야기',226);
insert into tblReview values (seqReview.nextval,5,80,'3번을 보아도 시간가는 줄 몰랐습니다',227);
insert into tblReview values (seqReview.nextval,4,20,'개인적으로 완전 만족하면서 봤음 강추bb',228);
insert into tblReview values (seqReview.nextval,1,20,'슬픔이 있어야 행복이 존재한다.',229);
insert into tblReview values (seqReview.nextval,1,80,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',230);
insert into tblReview values (seqReview.nextval,2,60,'한 소년과 한 소녀 그리고 그들만의 판타지',231);
insert into tblReview values (seqReview.nextval,2,100,'왜 평점이 높은지 모르겠음',232);
insert into tblReview values (seqReview.nextval,3,40,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',233);
insert into tblReview values (seqReview.nextval,5,40,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',234);
insert into tblReview values (seqReview.nextval,2,60,'3번을 보아도 시간가는 줄 몰랐습니다',235);
insert into tblReview values (seqReview.nextval,5,80,'몰입도 짱짱ㅜㅜ',236);
insert into tblReview values (seqReview.nextval,2,40,'꿀잼',237);
insert into tblReview values (seqReview.nextval,3,80,'감정을 억제하기보다 보듬어야 하는 이유.',238);
insert into tblReview values (seqReview.nextval,1,60,'재밌어요',239);
insert into tblReview values (seqReview.nextval,5,20,'위로를 주는 존재와 목소리',240);
insert into tblReview values (seqReview.nextval,4,80,'우리는 매일매일 행복한 연대를',241);
insert into tblReview values (seqReview.nextval,4,40,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',242);
insert into tblReview values (seqReview.nextval,4,80,'꿀잼',243);
insert into tblReview values (seqReview.nextval,2,60,'모르겠다. 그냥 펑펑 울었다..',244);
insert into tblReview values (seqReview.nextval,5,40,'사랑하는 사람과 함께라면 어디든 낙원이다.',245);
insert into tblReview values (seqReview.nextval,2,20,'언제 봐도 좋습니다 ~~!^^',246);
insert into tblReview values (seqReview.nextval,3,40,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',247);
insert into tblReview values (seqReview.nextval,3,20,'3번을 보아도 시간가는 줄 몰랐습니다',248);
insert into tblReview values (seqReview.nextval,4,20,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',249);
insert into tblReview values (seqReview.nextval,5,60,'기대이상으로 너무 재밌어요',250);
insert into tblReview values (seqReview.nextval,1,60,'저는 약간 지루했네요;;',251);
insert into tblReview values (seqReview.nextval,3,80,'생각보다 유치했어요',252);
insert into tblReview values (seqReview.nextval,5,80,'동심으로 떠나는 여행...? 좀 부족하다...',253);
insert into tblReview values (seqReview.nextval,4,80,'개인적으로 완전 만족하면서 봤음 강추bb',254);
insert into tblReview values (seqReview.nextval,4,80,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',255);
insert into tblReview values (seqReview.nextval,1,40,'한 소년과 한 소녀 그리고 그들만의 판타지',256);
insert into tblReview values (seqReview.nextval,4,40,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',257);
insert into tblReview values (seqReview.nextval,1,40,'슬픔이 있어야 행복이 존재한다.',258);
insert into tblReview values (seqReview.nextval,1,100,'저는 약간 지루했네요;;',259);
insert into tblReview values (seqReview.nextval,2,60,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',260);
insert into tblReview values (seqReview.nextval,3,40,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',261);
insert into tblReview values (seqReview.nextval,1,60,'재밌어요',262);
insert into tblReview values (seqReview.nextval,3,60,'3번을 보아도 시간가는 줄 몰랐습니다',263);
insert into tblReview values (seqReview.nextval,3,80,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',264);
insert into tblReview values (seqReview.nextval,4,60,'개인적으로 완전 만족하면서 봤음 강추bb',265);
insert into tblReview values (seqReview.nextval,1,80,'생각보다 유치했어요',266);
insert into tblReview values (seqReview.nextval,4,40,'동심으로 떠나는 여행...? 좀 부족하다...',267);
insert into tblReview values (seqReview.nextval,5,60,'왜 평점이 높은지 모르겠음',268);
insert into tblReview values (seqReview.nextval,4,40,'모르겠다. 그냥 펑펑 울었다..',269);
insert into tblReview values (seqReview.nextval,1,20,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',270);
insert into tblReview values (seqReview.nextval,3,40,'언제 봐도 좋습니다 ~~!^^',271);
insert into tblReview values (seqReview.nextval,1,100,'이 시리지는 다 봐야겠음.',272);
insert into tblReview values (seqReview.nextval,1,80,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',273);
insert into tblReview values (seqReview.nextval,2,80,'청춘이란 이유로 용기낼 수 있는 해가 뜨기 전 하룻밤까지만',274);
insert into tblReview values (seqReview.nextval,2,20,'길을 잃어야 길을 찾는법을 안다',275);
insert into tblReview values (seqReview.nextval,5,60,'이 시리지는 다 봐야겠음.',276);
insert into tblReview values (seqReview.nextval,1,40,'너무좋았습니다 주옥같은 대사들의 향연',277);
insert into tblReview values (seqReview.nextval,5,40,'언제 봐도 좋습니다 ~~!^^',278);
insert into tblReview values (seqReview.nextval,5,80,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',279);
insert into tblReview values (seqReview.nextval,3,100,'동화같은화면 동화같은이야기',280);
insert into tblReview values (seqReview.nextval,2,40,'재밌었어요 재미있게 봤습니당',281);
insert into tblReview values (seqReview.nextval,2,60,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',282);
insert into tblReview values (seqReview.nextval,4,40,'감정을 억제하기보다 보듬어야 하는 이유.',283);
insert into tblReview values (seqReview.nextval,5,40,'슬픔이 있어야 행복이 존재한다.',284);
insert into tblReview values (seqReview.nextval,2,100,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',285);
insert into tblReview values (seqReview.nextval,5,60,'너무좋았습니다 주옥같은 대사들의 향연',286);
insert into tblReview values (seqReview.nextval,2,80,'손에 꼽히는 인생캐릭터를 만난 것 같다',287);
insert into tblReview values (seqReview.nextval,3,40,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',288);
insert into tblReview values (seqReview.nextval,1,40,'3번을 보아도 시간가는 줄 몰랐습니다',289);
insert into tblReview values (seqReview.nextval,2,40,'별 다섯개를 오색으로 입히고 싶다.',290);
insert into tblReview values (seqReview.nextval,3,20,'모르겠다. 그냥 펑펑 울었다..',291);
insert into tblReview values (seqReview.nextval,1,80,'웨스앤더슨의 동화속에서 살고싶다.',292);
insert into tblReview values (seqReview.nextval,2,40,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',293);
insert into tblReview values (seqReview.nextval,2,60,'감동적입니다.',294);
insert into tblReview values (seqReview.nextval,5,20,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',295);
insert into tblReview values (seqReview.nextval,2,100,'언제 봐도 좋습니다 ~~!^^',296);
insert into tblReview values (seqReview.nextval,4,60,'길을 잃어야 길을 찾는법을 안다',297);
insert into tblReview values (seqReview.nextval,3,60,'개인적으로 완전 만족하면서 봤음 강추bb',298);
insert into tblReview values (seqReview.nextval,1,60,'This film is dedicated to our kids. Please don’t grow up. Ever',299);
insert into tblReview values (seqReview.nextval,2,100,'보는내내 답답합니다.정말 답답합니다.',300);
insert into tblReview values (seqReview.nextval,2,60,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',301);
insert into tblReview values (seqReview.nextval,4,100,'3번을 보아도 시간가는 줄 몰랐습니다',302);
insert into tblReview values (seqReview.nextval,5,60,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',303);
insert into tblReview values (seqReview.nextval,4,20,'보는내내 답답합니다.정말 답답합니다.',304);
insert into tblReview values (seqReview.nextval,5,80,'슬픔이 있어야 행복이 존재한다.',305);
insert into tblReview values (seqReview.nextval,2,20,'너무좋았습니다 주옥같은 대사들의 향연',306);
insert into tblReview values (seqReview.nextval,1,40,'꿀잼',307);
insert into tblReview values (seqReview.nextval,5,40,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',308);
insert into tblReview values (seqReview.nextval,3,40,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',309);
insert into tblReview values (seqReview.nextval,2,80,'길을 잃어야 길을 찾는법을 안다',310);
insert into tblReview values (seqReview.nextval,2,80,'개인적으로 완전 만족하면서 봤음 강추bb',311);
insert into tblReview values (seqReview.nextval,3,80,'꿀잼',312);
insert into tblReview values (seqReview.nextval,5,40,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',313);
insert into tblReview values (seqReview.nextval,3,40,'감정을 억제하기보다 보듬어야 하는 이유.',314);
insert into tblReview values (seqReview.nextval,5,40,'이 시리지는 다 봐야겠음.',315);
insert into tblReview values (seqReview.nextval,5,20,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',316);
insert into tblReview values (seqReview.nextval,5,60,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',317);
insert into tblReview values (seqReview.nextval,4,40,'우리는 매일매일 행복한 연대를',318);
insert into tblReview values (seqReview.nextval,1,20,'개인적으로 완전 만족하면서 봤음 강추bb',319);
insert into tblReview values (seqReview.nextval,3,20,'별 다섯개를 오색으로 입히고 싶다.',320);
insert into tblReview values (seqReview.nextval,1,40,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',321);
insert into tblReview values (seqReview.nextval,3,80,'재밌어요',322);
insert into tblReview values (seqReview.nextval,1,20,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',323);
insert into tblReview values (seqReview.nextval,5,100,'손에 꼽히는 인생캐릭터를 만난 것 같다',324);
insert into tblReview values (seqReview.nextval,1,20,'동심으로 떠나는 여행...? 좀 부족하다...',325);
insert into tblReview values (seqReview.nextval,4,20,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',326);
insert into tblReview values (seqReview.nextval,1,20,'꿀잼',327);
insert into tblReview values (seqReview.nextval,2,40,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',328);
insert into tblReview values (seqReview.nextval,4,20,'꿀잼',329);
insert into tblReview values (seqReview.nextval,1,60,'This film is dedicated to our kids. Please don’t grow up. Ever',330);
insert into tblReview values (seqReview.nextval,3,20,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',331);
insert into tblReview values (seqReview.nextval,2,20,'위로를 주는 존재와 목소리',332);
insert into tblReview values (seqReview.nextval,1,60,'감정을 억제하기보다 보듬어야 하는 이유.',333);
insert into tblReview values (seqReview.nextval,1,40,'왜 평점이 높은지 모르겠음',334);
insert into tblReview values (seqReview.nextval,1,40,'개인적으로 완전 만족하면서 봤음 강추bb',335);
insert into tblReview values (seqReview.nextval,1,100,'모르겠다. 그냥 펑펑 울었다..',336);
insert into tblReview values (seqReview.nextval,3,80,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',337);
insert into tblReview values (seqReview.nextval,5,100,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',338);
insert into tblReview values (seqReview.nextval,4,80,'한 소년과 한 소녀 그리고 그들만의 판타지',339);
insert into tblReview values (seqReview.nextval,2,40,'재미있다. 아름답다. 예쁘다.',340);
insert into tblReview values (seqReview.nextval,2,100,'동화같은화면 동화같은이야기',341);
insert into tblReview values (seqReview.nextval,4,60,'이 시리지는 다 봐야겠음.',342);
insert into tblReview values (seqReview.nextval,1,60,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',343);
insert into tblReview values (seqReview.nextval,2,80,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',344);
insert into tblReview values (seqReview.nextval,1,40,'너무좋았습니다 주옥같은 대사들의 향연',345);
insert into tblReview values (seqReview.nextval,2,40,'최근본거중에 레전드ㄷㄷ',346);
insert into tblReview values (seqReview.nextval,5,20,'길을 잃어야 길을 찾는법을 안다',347);
insert into tblReview values (seqReview.nextval,5,20,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',348);
insert into tblReview values (seqReview.nextval,2,80,'감동적입니다.',349);
insert into tblReview values (seqReview.nextval,2,60,'언제 봐도 좋습니다 ~~!^^',350);
insert into tblReview values (seqReview.nextval,3,40,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',351);
insert into tblReview values (seqReview.nextval,1,40,'길을 잃어야 길을 찾는법을 안다',352);
insert into tblReview values (seqReview.nextval,2,100,'슬픔이 있어야 행복이 존재한다.',353);
insert into tblReview values (seqReview.nextval,3,80,'청춘이란 이유로 용기낼 수 있는 해가 뜨기 전 하룻밤까지만',354);
insert into tblReview values (seqReview.nextval,3,60,'별 다섯개를 오색으로 입히고 싶다.',355);
insert into tblReview values (seqReview.nextval,1,40,'우리는 매일매일 행복한 연대를',356);
insert into tblReview values (seqReview.nextval,2,100,'개인적으로 완전 만족하면서 봤음 강추bb',357);
insert into tblReview values (seqReview.nextval,3,60,'기대이상으로 너무 재밌어요',358);
insert into tblReview values (seqReview.nextval,1,100,'감동적입니다.',359);
insert into tblReview values (seqReview.nextval,5,60,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',360);
insert into tblReview values (seqReview.nextval,3,40,'이 시리지는 다 봐야겠음.',361);
insert into tblReview values (seqReview.nextval,2,60,'한 소년과 한 소녀 그리고 그들만의 판타지',362);
insert into tblReview values (seqReview.nextval,5,100,'사랑하는 사람과 함께라면 어디든 낙원이다.',363);
insert into tblReview values (seqReview.nextval,4,80,'청춘이란 이유로 용기낼 수 있는 해가 뜨기 전 하룻밤까지만',364);
insert into tblReview values (seqReview.nextval,3,20,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',365);
insert into tblReview values (seqReview.nextval,4,20,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',366);
insert into tblReview values (seqReview.nextval,2,80,'동화같은화면 동화같은이야기',367);
insert into tblReview values (seqReview.nextval,1,40,'최근본거중에 레전드ㄷㄷ',368);
insert into tblReview values (seqReview.nextval,5,80,'위로를 주는 존재와 목소리',369);
insert into tblReview values (seqReview.nextval,3,100,'왜 평점이 높은지 모르겠음',370);
insert into tblReview values (seqReview.nextval,2,80,'동화같은화면 동화같은이야기',371);
insert into tblReview values (seqReview.nextval,2,60,'고전의 힘',372);
insert into tblReview values (seqReview.nextval,2,40,'This film is dedicated to our kids. Please don’t grow up. Ever',373);
insert into tblReview values (seqReview.nextval,4,100,'한 소년과 한 소녀 그리고 그들만의 판타지',374);
insert into tblReview values (seqReview.nextval,1,100,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',375);
insert into tblReview values (seqReview.nextval,4,100,'청춘이란 이유로 용기낼 수 있는 해가 뜨기 전 하룻밤까지만',376);
insert into tblReview values (seqReview.nextval,4,100,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',377);
insert into tblReview values (seqReview.nextval,5,20,'언제 봐도 좋습니다 ~~!^^',378);
insert into tblReview values (seqReview.nextval,5,100,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',379);
insert into tblReview values (seqReview.nextval,2,60,'기대이상으로 너무 재밌어요',380);
insert into tblReview values (seqReview.nextval,5,40,'위로를 주는 존재와 목소리',381);
insert into tblReview values (seqReview.nextval,1,100,'위로를 주는 존재와 목소리',382);
insert into tblReview values (seqReview.nextval,1,100,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',383);
insert into tblReview values (seqReview.nextval,4,20,'보는내내 답답합니다.정말 답답합니다.',384);
insert into tblReview values (seqReview.nextval,3,60,'꿀잼',385);
insert into tblReview values (seqReview.nextval,1,60,'왜 평점이 높은지 모르겠음',386);
insert into tblReview values (seqReview.nextval,5,40,'위로를 주는 존재와 목소리',387);
insert into tblReview values (seqReview.nextval,1,80,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',388);
insert into tblReview values (seqReview.nextval,5,40,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',389);
insert into tblReview values (seqReview.nextval,4,100,'기대이상으로 너무 재밌어요',390);
insert into tblReview values (seqReview.nextval,1,80,'재밌었어요 재미있게 봤습니당',391);
insert into tblReview values (seqReview.nextval,1,80,'보는내내 답답합니다.정말 답답합니다.',392);
insert into tblReview values (seqReview.nextval,5,80,'꿀잼',393);
insert into tblReview values (seqReview.nextval,5,40,'재밌어요',394);
insert into tblReview values (seqReview.nextval,3,80,'손에 꼽히는 인생캐릭터를 만난 것 같다',395);
insert into tblReview values (seqReview.nextval,4,100,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',396);
insert into tblReview values (seqReview.nextval,3,80,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',397);
insert into tblReview values (seqReview.nextval,3,100,'왜 평점이 높은지 모르겠음',398);
insert into tblReview values (seqReview.nextval,2,100,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',399);
insert into tblReview values (seqReview.nextval,3,60,'최근본거중에 레전드ㄷㄷ',400);
insert into tblReview values (seqReview.nextval,5,20,'재밌어요',401);
insert into tblReview values (seqReview.nextval,1,80,'3번을 보아도 시간가는 줄 몰랐습니다',402);
insert into tblReview values (seqReview.nextval,2,60,'슬픔이 있어야 행복이 존재한다.',403);
insert into tblReview values (seqReview.nextval,1,40,'보는내내 답답합니다.정말 답답합니다.',404);
insert into tblReview values (seqReview.nextval,5,100,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',405);
insert into tblReview values (seqReview.nextval,3,100,'감동적입니다.',406);
insert into tblReview values (seqReview.nextval,5,60,'동심으로 떠나는 여행...? 좀 부족하다...',407);
insert into tblReview values (seqReview.nextval,5,40,'재미있다. 아름답다. 예쁘다.',408);
insert into tblReview values (seqReview.nextval,1,40,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',409);
insert into tblReview values (seqReview.nextval,1,60,'왜 평점이 높은지 모르겠음',410);
insert into tblReview values (seqReview.nextval,3,80,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',411);
insert into tblReview values (seqReview.nextval,2,80,'한 소년과 한 소녀 그리고 그들만의 판타지',412);
insert into tblReview values (seqReview.nextval,4,20,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',413);
insert into tblReview values (seqReview.nextval,4,100,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',414);
insert into tblReview values (seqReview.nextval,3,100,'손에 꼽히는 인생캐릭터를 만난 것 같다',415);
insert into tblReview values (seqReview.nextval,4,100,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',416);
insert into tblReview values (seqReview.nextval,2,60,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',417);
insert into tblReview values (seqReview.nextval,5,40,'재밌었어요 재미있게 봤습니당',418);
insert into tblReview values (seqReview.nextval,5,80,'언제 봐도 좋습니다 ~~!^^',419);
insert into tblReview values (seqReview.nextval,3,20,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',420);
insert into tblReview values (seqReview.nextval,1,60,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',421);
insert into tblReview values (seqReview.nextval,3,20,'보는내내 답답합니다.정말 답답합니다.',422);
insert into tblReview values (seqReview.nextval,4,40,'재미있다. 아름답다. 예쁘다.',423);
insert into tblReview values (seqReview.nextval,1,40,'저는 약간 지루했네요;;',424);
insert into tblReview values (seqReview.nextval,5,100,'재밌어요',425);
insert into tblReview values (seqReview.nextval,3,60,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',426);
insert into tblReview values (seqReview.nextval,2,60,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',427);
insert into tblReview values (seqReview.nextval,4,100,'동심으로 떠나는 여행...? 좀 부족하다...',428);
insert into tblReview values (seqReview.nextval,4,80,'저는 약간 지루했네요;;',429);
insert into tblReview values (seqReview.nextval,1,20,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',430);
insert into tblReview values (seqReview.nextval,5,100,'길을 잃어야 길을 찾는법을 안다',431);
insert into tblReview values (seqReview.nextval,5,40,'최근본거중에 레전드ㄷㄷ',432);
insert into tblReview values (seqReview.nextval,4,100,'한 소년과 한 소녀 그리고 그들만의 판타지',433);
insert into tblReview values (seqReview.nextval,4,40,'별 다섯개를 오색으로 입히고 싶다.',434);
insert into tblReview values (seqReview.nextval,4,20,'저는 약간 지루했네요;;',435);
insert into tblReview values (seqReview.nextval,1,80,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',436);
insert into tblReview values (seqReview.nextval,2,20,'손에 꼽히는 인생캐릭터를 만난 것 같다',437);
insert into tblReview values (seqReview.nextval,2,20,'동심으로 떠나는 여행...? 좀 부족하다...',438);
insert into tblReview values (seqReview.nextval,5,20,'너무좋았습니다 주옥같은 대사들의 향연',439);
insert into tblReview values (seqReview.nextval,2,20,'모르겠다. 그냥 펑펑 울었다..',440);
insert into tblReview values (seqReview.nextval,5,80,'길을 잃어야 길을 찾는법을 안다',441);
insert into tblReview values (seqReview.nextval,1,40,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',442);
insert into tblReview values (seqReview.nextval,4,40,'위로를 주는 존재와 목소리',443);
insert into tblReview values (seqReview.nextval,5,80,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',444);
insert into tblReview values (seqReview.nextval,2,40,'재밌었어요 재미있게 봤습니당',445);
insert into tblReview values (seqReview.nextval,3,20,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',446);
insert into tblReview values (seqReview.nextval,2,60,'꿀잼',447);
insert into tblReview values (seqReview.nextval,5,100,'기대이상으로 너무 재밌어요',448);
insert into tblReview values (seqReview.nextval,3,80,'언제 봐도 좋습니다 ~~!^^',449);
insert into tblReview values (seqReview.nextval,5,100,'몰입도 짱짱ㅜㅜ',450);
insert into tblReview values (seqReview.nextval,1,60,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',451);
insert into tblReview values (seqReview.nextval,4,80,'생각보다 유치했어요',452);
insert into tblReview values (seqReview.nextval,2,20,'이 시리지는 다 봐야겠음.',453);
insert into tblReview values (seqReview.nextval,1,40,'3번을 보아도 시간가는 줄 몰랐습니다',454);
insert into tblReview values (seqReview.nextval,1,40,'한 소년과 한 소녀 그리고 그들만의 판타지',455);
insert into tblReview values (seqReview.nextval,3,60,'한 소년과 한 소녀 그리고 그들만의 판타지',456);
insert into tblReview values (seqReview.nextval,1,40,'저는 약간 지루했네요;;',457);
insert into tblReview values (seqReview.nextval,2,20,'모르겠다. 그냥 펑펑 울었다..',458);
insert into tblReview values (seqReview.nextval,2,80,'웨스앤더슨의 동화속에서 살고싶다.',459);
insert into tblReview values (seqReview.nextval,5,60,'이 시리지는 다 봐야겠음.',460);
insert into tblReview values (seqReview.nextval,4,20,'이 시리지는 다 봐야겠음.',461);
insert into tblReview values (seqReview.nextval,1,40,'최근본거중에 레전드ㄷㄷ',462);
insert into tblReview values (seqReview.nextval,2,100,'고전의 힘',463);
insert into tblReview values (seqReview.nextval,5,100,'길을 잃어야 길을 찾는법을 안다',464);
insert into tblReview values (seqReview.nextval,3,40,'손에 꼽히는 인생캐릭터를 만난 것 같다',465);
insert into tblReview values (seqReview.nextval,5,100,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',466);
insert into tblReview values (seqReview.nextval,5,100,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',467);
insert into tblReview values (seqReview.nextval,4,60,'감동적입니다.',468);
insert into tblReview values (seqReview.nextval,2,20,'손에 꼽히는 인생캐릭터를 만난 것 같다',469);
insert into tblReview values (seqReview.nextval,3,40,'최근본거중에 레전드ㄷㄷ',470);
insert into tblReview values (seqReview.nextval,2,40,'동심으로 떠나는 여행...? 좀 부족하다...',471);
insert into tblReview values (seqReview.nextval,2,80,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',472);
insert into tblReview values (seqReview.nextval,2,40,'저는 약간 지루했네요;;',473);
insert into tblReview values (seqReview.nextval,2,40,'몰입도 짱짱ㅜㅜ',474);
insert into tblReview values (seqReview.nextval,2,100,'위로를 주는 존재와 목소리',475);
insert into tblReview values (seqReview.nextval,5,20,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',476);
insert into tblReview values (seqReview.nextval,5,80,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',477);
insert into tblReview values (seqReview.nextval,4,60,'기대이상으로 너무 재밌어요',478);
insert into tblReview values (seqReview.nextval,2,40,'생각보다 유치했어요',479);
insert into tblReview values (seqReview.nextval,5,40,'한 소년과 한 소녀 그리고 그들만의 판타지',480);
insert into tblReview values (seqReview.nextval,4,80,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',481);
insert into tblReview values (seqReview.nextval,3,40,'This film is dedicated to our kids. Please don’t grow up. Ever',482);
insert into tblReview values (seqReview.nextval,2,20,'위로를 주는 존재와 목소리',483);
insert into tblReview values (seqReview.nextval,4,60,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',484);
insert into tblReview values (seqReview.nextval,4,20,'길을 잃어야 길을 찾는법을 안다',485);
insert into tblReview values (seqReview.nextval,1,20,'생각보다 유치했어요',486);
insert into tblReview values (seqReview.nextval,2,20,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',487);
insert into tblReview values (seqReview.nextval,2,60,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',488);
insert into tblReview values (seqReview.nextval,3,60,'사랑하는 사람과 함께라면 어디든 낙원이다.',489);
insert into tblReview values (seqReview.nextval,5,100,'모르겠다. 그냥 펑펑 울었다..',490);
insert into tblReview values (seqReview.nextval,5,60,'왜 평점이 높은지 모르겠음',491);
insert into tblReview values (seqReview.nextval,5,60,'개인적으로 완전 만족하면서 봤음 강추bb',492);
insert into tblReview values (seqReview.nextval,5,60,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',493);
insert into tblReview values (seqReview.nextval,3,100,'감정을 억제하기보다 보듬어야 하는 이유.',494);
insert into tblReview values (seqReview.nextval,1,40,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',495);
insert into tblReview values (seqReview.nextval,1,100,'웨스앤더슨의 동화속에서 살고싶다.',496);
insert into tblReview values (seqReview.nextval,1,60,'손에 꼽히는 인생캐릭터를 만난 것 같다',497);
insert into tblReview values (seqReview.nextval,2,40,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',498);
insert into tblReview values (seqReview.nextval,3,60,'동심으로 떠나는 여행...? 좀 부족하다...',499);
insert into tblReview values (seqReview.nextval,4,40,'고전의 힘',500);
insert into tblReview values (seqReview.nextval,3,20,'재밌었어요 재미있게 봤습니당',501);
insert into tblReview values (seqReview.nextval,5,100,'재미있다. 아름답다. 예쁘다.',502);
insert into tblReview values (seqReview.nextval,4,100,'너무좋았습니다 주옥같은 대사들의 향연',503);
insert into tblReview values (seqReview.nextval,1,60,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',504);
insert into tblReview values (seqReview.nextval,2,100,'별 다섯개를 오색으로 입히고 싶다.',505);
insert into tblReview values (seqReview.nextval,5,20,'재미있다. 아름답다. 예쁘다.',506);
insert into tblReview values (seqReview.nextval,3,40,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',507);
insert into tblReview values (seqReview.nextval,1,20,'감정을 억제하기보다 보듬어야 하는 이유.',508);
insert into tblReview values (seqReview.nextval,1,80,'언제 봐도 좋습니다 ~~!^^',509);
insert into tblReview values (seqReview.nextval,5,80,'손에 꼽히는 인생캐릭터를 만난 것 같다',510);
insert into tblReview values (seqReview.nextval,5,60,'왜 평점이 높은지 모르겠음',511);
insert into tblReview values (seqReview.nextval,2,60,'별 다섯개를 오색으로 입히고 싶다.',512);
insert into tblReview values (seqReview.nextval,2,100,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',513);
insert into tblReview values (seqReview.nextval,3,80,'몰입도 짱짱ㅜㅜ',514);
insert into tblReview values (seqReview.nextval,1,40,'길을 잃어야 길을 찾는법을 안다',515);
insert into tblReview values (seqReview.nextval,1,40,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',516);
insert into tblReview values (seqReview.nextval,3,100,'언제 봐도 좋습니다 ~~!^^',517);
insert into tblReview values (seqReview.nextval,1,60,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',518);
insert into tblReview values (seqReview.nextval,5,60,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',519);
insert into tblReview values (seqReview.nextval,1,80,'슬픔이 있어야 행복이 존재한다.',520);
insert into tblReview values (seqReview.nextval,3,20,'3번을 보아도 시간가는 줄 몰랐습니다',521);
insert into tblReview values (seqReview.nextval,5,20,'저는 약간 지루했네요;;',522);
insert into tblReview values (seqReview.nextval,3,40,'몰입도 짱짱ㅜㅜ',523);
insert into tblReview values (seqReview.nextval,1,80,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',524);
insert into tblReview values (seqReview.nextval,3,60,'감정을 억제하기보다 보듬어야 하는 이유.',525);
insert into tblReview values (seqReview.nextval,2,100,'저는 약간 지루했네요;;',526);
insert into tblReview values (seqReview.nextval,2,100,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',527);
insert into tblReview values (seqReview.nextval,3,100,'고전의 힘',528);
insert into tblReview values (seqReview.nextval,5,60,'언제 봐도 좋습니다 ~~!^^',529);
insert into tblReview values (seqReview.nextval,2,40,'This film is dedicated to our kids. Please don’t grow up. Ever',530);
insert into tblReview values (seqReview.nextval,3,20,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',531);
insert into tblReview values (seqReview.nextval,1,20,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',532);
insert into tblReview values (seqReview.nextval,3,60,'꿀잼',533);
insert into tblReview values (seqReview.nextval,2,100,'생각보다 유치했어요',534);
insert into tblReview values (seqReview.nextval,1,40,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',535);
insert into tblReview values (seqReview.nextval,3,60,'사랑하는 사람과 함께라면 어디든 낙원이다.',536);
insert into tblReview values (seqReview.nextval,5,100,'왜 평점이 높은지 모르겠음',537);
insert into tblReview values (seqReview.nextval,3,20,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',538);
insert into tblReview values (seqReview.nextval,3,60,'모르겠다. 그냥 펑펑 울었다..',539);
insert into tblReview values (seqReview.nextval,5,100,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',540);
insert into tblReview values (seqReview.nextval,2,80,'재밌었어요 재미있게 봤습니당',541);
insert into tblReview values (seqReview.nextval,3,100,'This film is dedicated to our kids. Please don’t grow up. Ever',542);
insert into tblReview values (seqReview.nextval,3,60,'슬픔이 있어야 행복이 존재한다.',543);
insert into tblReview values (seqReview.nextval,2,80,'고전의 힘',544);
insert into tblReview values (seqReview.nextval,1,80,'동화같은화면 동화같은이야기',545);
insert into tblReview values (seqReview.nextval,5,20,'감동적입니다.',546);
insert into tblReview values (seqReview.nextval,4,40,'왜 평점이 높은지 모르겠음',547);
insert into tblReview values (seqReview.nextval,4,20,'동화같은화면 동화같은이야기',548);
insert into tblReview values (seqReview.nextval,3,80,'웨스앤더슨의 동화속에서 살고싶다.',549);
insert into tblReview values (seqReview.nextval,1,20,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',550);
insert into tblReview values (seqReview.nextval,2,60,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',551);
insert into tblReview values (seqReview.nextval,1,100,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',552);
insert into tblReview values (seqReview.nextval,4,60,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',553);
insert into tblReview values (seqReview.nextval,1,40,'이 시리지는 다 봐야겠음.',554);
insert into tblReview values (seqReview.nextval,3,40,'보는내내 답답합니다.정말 답답합니다.',555);
insert into tblReview values (seqReview.nextval,1,40,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',556);
insert into tblReview values (seqReview.nextval,1,20,'모르겠다. 그냥 펑펑 울었다..',557);
insert into tblReview values (seqReview.nextval,4,100,'왜 평점이 높은지 모르겠음',558);
insert into tblReview values (seqReview.nextval,1,40,'모르겠다. 그냥 펑펑 울었다..',559);
insert into tblReview values (seqReview.nextval,2,80,'This film is dedicated to our kids. Please don’t grow up. Ever',560);
insert into tblReview values (seqReview.nextval,4,40,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',561);
insert into tblReview values (seqReview.nextval,3,80,'한 소년과 한 소녀 그리고 그들만의 판타지',562);
insert into tblReview values (seqReview.nextval,4,100,'생각보다 유치했어요',563);
insert into tblReview values (seqReview.nextval,3,100,'꿀잼',564);
insert into tblReview values (seqReview.nextval,1,60,'감동적입니다.',565);
insert into tblReview values (seqReview.nextval,5,60,'최근본거중에 레전드ㄷㄷ',566);
insert into tblReview values (seqReview.nextval,5,60,'꿀잼',567);
insert into tblReview values (seqReview.nextval,1,80,'위로를 주는 존재와 목소리',568);
insert into tblReview values (seqReview.nextval,2,60,'별 다섯개를 오색으로 입히고 싶다.',569);
insert into tblReview values (seqReview.nextval,1,20,'보는내내 답답합니다.정말 답답합니다.',570);
insert into tblReview values (seqReview.nextval,3,100,'사랑하는 사람과 함께라면 어디든 낙원이다.',571);
insert into tblReview values (seqReview.nextval,2,40,'재밌어요',572);
insert into tblReview values (seqReview.nextval,2,60,'재미있다. 아름답다. 예쁘다.',573);
insert into tblReview values (seqReview.nextval,4,60,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',574);
insert into tblReview values (seqReview.nextval,5,20,'손에 꼽히는 인생캐릭터를 만난 것 같다',575);
insert into tblReview values (seqReview.nextval,1,40,'This film is dedicated to our kids. Please don’t grow up. Ever',576);
insert into tblReview values (seqReview.nextval,4,100,'별 다섯개를 오색으로 입히고 싶다.',577);
insert into tblReview values (seqReview.nextval,3,20,'저는 약간 지루했네요;;',578);
insert into tblReview values (seqReview.nextval,1,60,'재밌었어요 재미있게 봤습니당',579);
insert into tblReview values (seqReview.nextval,5,60,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',580);
insert into tblReview values (seqReview.nextval,4,60,'이 시리지는 다 봐야겠음.',581);
insert into tblReview values (seqReview.nextval,5,100,'별 다섯개를 오색으로 입히고 싶다.',582);
insert into tblReview values (seqReview.nextval,2,100,'우리는 매일매일 행복한 연대를',583);
insert into tblReview values (seqReview.nextval,3,80,'보는내내 답답합니다.정말 답답합니다.',584);
insert into tblReview values (seqReview.nextval,5,80,'손에 꼽히는 인생캐릭터를 만난 것 같다',585);
insert into tblReview values (seqReview.nextval,2,40,'감정을 억제하기보다 보듬어야 하는 이유.',586);
insert into tblReview values (seqReview.nextval,1,80,'한 소년과 한 소녀 그리고 그들만의 판타지',587);
insert into tblReview values (seqReview.nextval,3,60,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',588);
insert into tblReview values (seqReview.nextval,2,100,'손에 꼽히는 인생캐릭터를 만난 것 같다',589);
insert into tblReview values (seqReview.nextval,4,60,'재밌었어요 재미있게 봤습니당',590);
insert into tblReview values (seqReview.nextval,4,100,'사랑하는 사람과 함께라면 어디든 낙원이다.',591);
insert into tblReview values (seqReview.nextval,1,60,'저는 약간 지루했네요;;',592);
insert into tblReview values (seqReview.nextval,5,40,'재밌어요',593);
insert into tblReview values (seqReview.nextval,2,20,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',594);
insert into tblReview values (seqReview.nextval,2,80,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',595);
insert into tblReview values (seqReview.nextval,4,100,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',596);
insert into tblReview values (seqReview.nextval,4,100,'이 시리지는 다 봐야겠음.',597);
insert into tblReview values (seqReview.nextval,2,80,'개인적으로 완전 만족하면서 봤음 강추bb',598);
insert into tblReview values (seqReview.nextval,5,80,'고전의 힘',599);
insert into tblReview values (seqReview.nextval,5,80,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',600);
insert into tblReview values (seqReview.nextval,1,80,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',601);
insert into tblReview values (seqReview.nextval,1,20,'이 시리지는 다 봐야겠음.',602);
insert into tblReview values (seqReview.nextval,4,40,'슬픔이 있어야 행복이 존재한다.',603);
insert into tblReview values (seqReview.nextval,3,20,'언제 봐도 좋습니다 ~~!^^',604);
insert into tblReview values (seqReview.nextval,5,100,'위로를 주는 존재와 목소리',605);
insert into tblReview values (seqReview.nextval,2,100,'왜 평점이 높은지 모르겠음',606);
insert into tblReview values (seqReview.nextval,2,100,'꿀잼',607);
insert into tblReview values (seqReview.nextval,1,40,'생각보다 유치했어요',608);
insert into tblReview values (seqReview.nextval,5,80,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',609);
insert into tblReview values (seqReview.nextval,3,80,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',610);
insert into tblReview values (seqReview.nextval,2,20,'별 다섯개를 오색으로 입히고 싶다.',611);
insert into tblReview values (seqReview.nextval,4,20,'한 소년과 한 소녀 그리고 그들만의 판타지',612);
insert into tblReview values (seqReview.nextval,5,60,'저는 약간 지루했네요;;',613);
insert into tblReview values (seqReview.nextval,5,40,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',614);
insert into tblReview values (seqReview.nextval,1,20,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',615);
insert into tblReview values (seqReview.nextval,3,100,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',616);
insert into tblReview values (seqReview.nextval,3,60,'위로를 주는 존재와 목소리',617);
insert into tblReview values (seqReview.nextval,5,80,'재밌어요',618);
insert into tblReview values (seqReview.nextval,3,100,'고전의 힘',619);
insert into tblReview values (seqReview.nextval,4,20,'언제 봐도 좋습니다 ~~!^^',620);
insert into tblReview values (seqReview.nextval,2,20,'위로를 주는 존재와 목소리',621);
insert into tblReview values (seqReview.nextval,5,60,'감동적입니다.',622);
insert into tblReview values (seqReview.nextval,4,60,'이 시리지는 다 봐야겠음.',623);
insert into tblReview values (seqReview.nextval,3,40,'재밌어요',624);
insert into tblReview values (seqReview.nextval,5,20,'웨스앤더슨의 동화속에서 살고싶다.',625);
insert into tblReview values (seqReview.nextval,4,80,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',626);
insert into tblReview values (seqReview.nextval,3,80,'재밌었어요 재미있게 봤습니당',627);
insert into tblReview values (seqReview.nextval,4,80,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',628);
insert into tblReview values (seqReview.nextval,4,60,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',629);
insert into tblReview values (seqReview.nextval,2,20,'길을 잃어야 길을 찾는법을 안다',630);
insert into tblReview values (seqReview.nextval,4,40,'언제 봐도 좋습니다 ~~!^^',631);
insert into tblReview values (seqReview.nextval,2,60,'동화같은화면 동화같은이야기',632);
insert into tblReview values (seqReview.nextval,3,20,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',633);
insert into tblReview values (seqReview.nextval,4,100,'This film is dedicated to our kids. Please don’t grow up. Ever',634);
insert into tblReview values (seqReview.nextval,2,100,'This film is dedicated to our kids. Please don’t grow up. Ever',635);
insert into tblReview values (seqReview.nextval,4,60,'언제 봐도 좋습니다 ~~!^^',636);
insert into tblReview values (seqReview.nextval,3,40,'언제 봐도 좋습니다 ~~!^^',637);
insert into tblReview values (seqReview.nextval,1,40,'기대이상으로 너무 재밌어요',638);
insert into tblReview values (seqReview.nextval,3,80,'감동적입니다.',639);
insert into tblReview values (seqReview.nextval,3,80,'길을 잃어야 길을 찾는법을 안다',640);
insert into tblReview values (seqReview.nextval,2,80,'고전의 힘',641);
insert into tblReview values (seqReview.nextval,4,80,'사랑하는 사람과 함께라면 어디든 낙원이다.',642);
insert into tblReview values (seqReview.nextval,1,100,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',643);
insert into tblReview values (seqReview.nextval,3,40,'개인적으로 완전 만족하면서 봤음 강추bb',644);
insert into tblReview values (seqReview.nextval,1,60,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',645);
insert into tblReview values (seqReview.nextval,2,40,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',646);
insert into tblReview values (seqReview.nextval,2,60,'몰입도 짱짱ㅜㅜ',647);
insert into tblReview values (seqReview.nextval,4,40,'고전의 힘',648);
insert into tblReview values (seqReview.nextval,5,20,'너무좋았습니다 주옥같은 대사들의 향연',649);
insert into tblReview values (seqReview.nextval,5,40,'손에 꼽히는 인생캐릭터를 만난 것 같다',650);
insert into tblReview values (seqReview.nextval,3,40,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',651);
insert into tblReview values (seqReview.nextval,1,40,'꿀잼',652);
insert into tblReview values (seqReview.nextval,3,80,'고전의 힘',653);
insert into tblReview values (seqReview.nextval,3,80,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',654);
insert into tblReview values (seqReview.nextval,3,40,'재밌어요',655);
insert into tblReview values (seqReview.nextval,3,20,'보는내내 답답합니다.정말 답답합니다.',656);
insert into tblReview values (seqReview.nextval,1,80,'3번을 보아도 시간가는 줄 몰랐습니다',657);
insert into tblReview values (seqReview.nextval,4,60,'재미있다. 아름답다. 예쁘다.',658);
insert into tblReview values (seqReview.nextval,1,100,'재밌어요',659);
insert into tblReview values (seqReview.nextval,3,20,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',660);
insert into tblReview values (seqReview.nextval,3,20,'재미있다. 아름답다. 예쁘다.',661);
insert into tblReview values (seqReview.nextval,3,20,'몰입도 짱짱ㅜㅜ',662);
insert into tblReview values (seqReview.nextval,3,60,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',663);
insert into tblReview values (seqReview.nextval,4,80,'재밌어요',664);
insert into tblReview values (seqReview.nextval,4,80,'언제 봐도 좋습니다 ~~!^^',665);
insert into tblReview values (seqReview.nextval,1,80,'재미있다. 아름답다. 예쁘다.',666);
insert into tblReview values (seqReview.nextval,1,100,'별 다섯개를 오색으로 입히고 싶다.',667);
insert into tblReview values (seqReview.nextval,4,40,'언제 봐도 좋습니다 ~~!^^',668);
insert into tblReview values (seqReview.nextval,2,40,'생각보다 유치했어요',669);
insert into tblReview values (seqReview.nextval,3,80,'동화같은화면 동화같은이야기',670);
insert into tblReview values (seqReview.nextval,5,80,'웨스앤더슨의 동화속에서 살고싶다.',671);
insert into tblReview values (seqReview.nextval,1,100,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',672);
insert into tblReview values (seqReview.nextval,5,80,'보는내내 답답합니다.정말 답답합니다.',673);
insert into tblReview values (seqReview.nextval,3,40,'동심으로 떠나는 여행...? 좀 부족하다...',674);
insert into tblReview values (seqReview.nextval,1,60,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',675);
insert into tblReview values (seqReview.nextval,1,20,'왜 평점이 높은지 모르겠음',676);
insert into tblReview values (seqReview.nextval,4,60,'3번을 보아도 시간가는 줄 몰랐습니다',677);
insert into tblReview values (seqReview.nextval,1,40,'동화같은화면 동화같은이야기',678);
insert into tblReview values (seqReview.nextval,2,80,'재밌었어요 재미있게 봤습니당',679);
insert into tblReview values (seqReview.nextval,5,20,'고전의 힘',680);
insert into tblReview values (seqReview.nextval,1,40,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',681);
insert into tblReview values (seqReview.nextval,1,60,'생각보다 유치했어요',682);
insert into tblReview values (seqReview.nextval,5,100,'동심으로 떠나는 여행...? 좀 부족하다...',683);
insert into tblReview values (seqReview.nextval,4,40,'고전의 힘',684);
insert into tblReview values (seqReview.nextval,4,60,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',685);
insert into tblReview values (seqReview.nextval,4,100,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',686);
insert into tblReview values (seqReview.nextval,4,80,'웨스앤더슨의 동화속에서 살고싶다.',687);
insert into tblReview values (seqReview.nextval,2,100,'동심으로 떠나는 여행...? 좀 부족하다...',688);
insert into tblReview values (seqReview.nextval,2,80,'생각보다 유치했어요',689);
insert into tblReview values (seqReview.nextval,5,60,'이 시리지는 다 봐야겠음.',690);
insert into tblReview values (seqReview.nextval,2,60,'길을 잃어야 길을 찾는법을 안다',691);
insert into tblReview values (seqReview.nextval,4,40,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',692);
insert into tblReview values (seqReview.nextval,2,20,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',693);
insert into tblReview values (seqReview.nextval,3,80,'너무좋았습니다 주옥같은 대사들의 향연',694);
insert into tblReview values (seqReview.nextval,3,80,'3번을 보아도 시간가는 줄 몰랐습니다',695);
insert into tblReview values (seqReview.nextval,3,60,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',696);
insert into tblReview values (seqReview.nextval,1,60,'보는내내 답답합니다.정말 답답합니다.',697);
insert into tblReview values (seqReview.nextval,4,20,'모르겠다. 그냥 펑펑 울었다..',698);
insert into tblReview values (seqReview.nextval,2,40,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',699);
insert into tblReview values (seqReview.nextval,5,20,'길을 잃어야 길을 찾는법을 안다',700);
insert into tblReview values (seqReview.nextval,4,60,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',701);
insert into tblReview values (seqReview.nextval,2,100,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',702);
insert into tblReview values (seqReview.nextval,4,80,'꿀잼',703);
insert into tblReview values (seqReview.nextval,5,80,'보는내내 답답합니다.정말 답답합니다.',704);
insert into tblReview values (seqReview.nextval,5,60,'슬픔이 있어야 행복이 존재한다.',705);
insert into tblReview values (seqReview.nextval,3,100,'재밌어요',706);
insert into tblReview values (seqReview.nextval,2,80,'청춘이란 이유로 용기낼 수 있는 해가 뜨기 전 하룻밤까지만',707);
insert into tblReview values (seqReview.nextval,3,100,'이 시리지는 다 봐야겠음.',708);
insert into tblReview values (seqReview.nextval,5,60,'기대이상으로 너무 재밌어요',709);
insert into tblReview values (seqReview.nextval,4,100,'꿀잼',710);
insert into tblReview values (seqReview.nextval,1,80,'재밌었어요 재미있게 봤습니당',711);
insert into tblReview values (seqReview.nextval,3,20,'별 다섯개를 오색으로 입히고 싶다.',712);
insert into tblReview values (seqReview.nextval,1,80,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',713);
insert into tblReview values (seqReview.nextval,2,20,'감정을 억제하기보다 보듬어야 하는 이유.',714);
insert into tblReview values (seqReview.nextval,2,40,'개인적으로 완전 만족하면서 봤음 강추bb',715);
insert into tblReview values (seqReview.nextval,1,100,'꿀잼',716);
insert into tblReview values (seqReview.nextval,1,60,'생각보다 유치했어요',717);
insert into tblReview values (seqReview.nextval,1,100,'꿀잼',718);
insert into tblReview values (seqReview.nextval,2,20,'감정을 억제하기보다 보듬어야 하는 이유.',719);
insert into tblReview values (seqReview.nextval,1,60,'슬픔이 있어야 행복이 존재한다.',720);
insert into tblReview values (seqReview.nextval,1,40,'사랑하는 사람과 함께라면 어디든 낙원이다.',721);
insert into tblReview values (seqReview.nextval,1,40,'우리는 매일매일 행복한 연대를',722);
insert into tblReview values (seqReview.nextval,2,100,'재미있다. 아름답다. 예쁘다.',723);
insert into tblReview values (seqReview.nextval,5,40,'슬픔이 있어야 행복이 존재한다.',724);
insert into tblReview values (seqReview.nextval,3,80,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',725);
insert into tblReview values (seqReview.nextval,4,40,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',726);
insert into tblReview values (seqReview.nextval,5,20,'웨스앤더슨의 동화속에서 살고싶다.',727);
insert into tblReview values (seqReview.nextval,4,40,'감동적입니다.',728);
insert into tblReview values (seqReview.nextval,4,20,'최근본거중에 레전드ㄷㄷ',729);
insert into tblReview values (seqReview.nextval,3,40,'3번을 보아도 시간가는 줄 몰랐습니다',730);
insert into tblReview values (seqReview.nextval,1,100,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',731);
insert into tblReview values (seqReview.nextval,3,60,'최근본거중에 레전드ㄷㄷ',732);
insert into tblReview values (seqReview.nextval,5,80,'별 다섯개를 오색으로 입히고 싶다.',733);
insert into tblReview values (seqReview.nextval,3,100,'한 소년과 한 소녀 그리고 그들만의 판타지',734);
insert into tblReview values (seqReview.nextval,3,80,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',735);
insert into tblReview values (seqReview.nextval,4,100,'재밌어요',736);
insert into tblReview values (seqReview.nextval,4,80,'감동적입니다.',737);
insert into tblReview values (seqReview.nextval,5,100,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',738);
insert into tblReview values (seqReview.nextval,3,80,'저는 약간 지루했네요;;',739);
insert into tblReview values (seqReview.nextval,5,60,'웨스앤더슨의 동화속에서 살고싶다.',740);
insert into tblReview values (seqReview.nextval,5,100,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',741);
insert into tblReview values (seqReview.nextval,3,100,'3번을 보아도 시간가는 줄 몰랐습니다',742);
insert into tblReview values (seqReview.nextval,2,100,'생각보다 유치했어요',743);
insert into tblReview values (seqReview.nextval,2,40,'This film is dedicated to our kids. Please don’t grow up. Ever',744);
insert into tblReview values (seqReview.nextval,1,80,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',745);
insert into tblReview values (seqReview.nextval,5,60,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',746);
insert into tblReview values (seqReview.nextval,4,60,'재밌었어요 재미있게 봤습니당',747);
insert into tblReview values (seqReview.nextval,4,60,'재밌었어요 재미있게 봤습니당',748);
insert into tblReview values (seqReview.nextval,4,40,'길을 잃어야 길을 찾는법을 안다',749);
insert into tblReview values (seqReview.nextval,4,40,'꿀잼',750);
insert into tblReview values (seqReview.nextval,5,80,'재밌어요',751);
insert into tblReview values (seqReview.nextval,4,100,'이 시리지는 다 봐야겠음.',752);
insert into tblReview values (seqReview.nextval,4,80,'동심으로 떠나는 여행...? 좀 부족하다...',753);
insert into tblReview values (seqReview.nextval,5,80,'재미있다. 아름답다. 예쁘다.',754);
insert into tblReview values (seqReview.nextval,2,100,'왜 평점이 높은지 모르겠음',755);
insert into tblReview values (seqReview.nextval,4,80,'몰입도 짱짱ㅜㅜ',756);
insert into tblReview values (seqReview.nextval,1,100,'최근본거중에 레전드ㄷㄷ',757);
insert into tblReview values (seqReview.nextval,2,60,'생각보다 유치했어요',758);
insert into tblReview values (seqReview.nextval,1,40,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',759);
insert into tblReview values (seqReview.nextval,4,60,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',760);
insert into tblReview values (seqReview.nextval,3,80,'웨스앤더슨의 동화속에서 살고싶다.',761);
insert into tblReview values (seqReview.nextval,5,20,'보는내내 답답합니다.정말 답답합니다.',762);
insert into tblReview values (seqReview.nextval,1,40,'왜 평점이 높은지 모르겠음',763);
insert into tblReview values (seqReview.nextval,3,100,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',764);
insert into tblReview values (seqReview.nextval,5,20,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',765);
insert into tblReview values (seqReview.nextval,5,80,'몰입도 짱짱ㅜㅜ',766);
insert into tblReview values (seqReview.nextval,1,60,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',767);
insert into tblReview values (seqReview.nextval,3,80,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',768);
insert into tblReview values (seqReview.nextval,3,80,'This film is dedicated to our kids. Please don’t grow up. Ever',769);
insert into tblReview values (seqReview.nextval,5,40,'동심으로 떠나는 여행...? 좀 부족하다...',770);
insert into tblReview values (seqReview.nextval,5,40,'몰입도 짱짱ㅜㅜ',771);
insert into tblReview values (seqReview.nextval,5,60,'청춘이란 이유로 용기낼 수 있는 해가 뜨기 전 하룻밤까지만',772);
insert into tblReview values (seqReview.nextval,5,60,'웨스앤더슨의 동화속에서 살고싶다.',773);
insert into tblReview values (seqReview.nextval,5,40,'보는내내 답답합니다.정말 답답합니다.',774);
insert into tblReview values (seqReview.nextval,5,40,'동심으로 떠나는 여행...? 좀 부족하다...',775);
insert into tblReview values (seqReview.nextval,5,40,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',776);
insert into tblReview values (seqReview.nextval,2,40,'별 다섯개를 오색으로 입히고 싶다.',777);
insert into tblReview values (seqReview.nextval,2,20,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',778);
insert into tblReview values (seqReview.nextval,4,100,'동심으로 떠나는 여행...? 좀 부족하다...',779);
insert into tblReview values (seqReview.nextval,4,100,'재밌었어요 재미있게 봤습니당',780);
insert into tblReview values (seqReview.nextval,3,60,'한 소년과 한 소녀 그리고 그들만의 판타지',781);
insert into tblReview values (seqReview.nextval,5,20,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',782);
insert into tblReview values (seqReview.nextval,2,100,'감정을 억제하기보다 보듬어야 하는 이유.',783);
insert into tblReview values (seqReview.nextval,4,20,'한 소년과 한 소녀 그리고 그들만의 판타지',784);
insert into tblReview values (seqReview.nextval,3,100,'웨스앤더슨의 동화속에서 살고싶다.',785);
insert into tblReview values (seqReview.nextval,2,20,'보는내내 답답합니다.정말 답답합니다.',786);
insert into tblReview values (seqReview.nextval,4,100,'별 다섯개를 오색으로 입히고 싶다.',787);
insert into tblReview values (seqReview.nextval,3,60,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',788);
insert into tblReview values (seqReview.nextval,3,100,'감정을 억제하기보다 보듬어야 하는 이유.',789);
insert into tblReview values (seqReview.nextval,1,100,'재미있다. 아름답다. 예쁘다.',790);
insert into tblReview values (seqReview.nextval,5,80,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',791);
insert into tblReview values (seqReview.nextval,4,80,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',792);
insert into tblReview values (seqReview.nextval,2,100,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',793);
insert into tblReview values (seqReview.nextval,2,80,'감정을 억제하기보다 보듬어야 하는 이유.',794);
insert into tblReview values (seqReview.nextval,5,80,'언제 봐도 좋습니다 ~~!^^',795);
insert into tblReview values (seqReview.nextval,2,80,'우리는 매일매일 행복한 연대를',796);
insert into tblReview values (seqReview.nextval,1,20,'재밌었어요 재미있게 봤습니당',797);
insert into tblReview values (seqReview.nextval,3,60,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',798);
insert into tblReview values (seqReview.nextval,5,100,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',799);
insert into tblReview values (seqReview.nextval,5,80,'생각보다 유치했어요',800);
insert into tblReview values (seqReview.nextval,4,20,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',801);
insert into tblReview values (seqReview.nextval,2,100,'우리는 매일매일 행복한 연대를',802);
insert into tblReview values (seqReview.nextval,4,80,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',803);
insert into tblReview values (seqReview.nextval,3,60,'꿀잼',804);
insert into tblReview values (seqReview.nextval,2,100,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',805);
insert into tblReview values (seqReview.nextval,3,80,'손에 꼽히는 인생캐릭터를 만난 것 같다',806);
insert into tblReview values (seqReview.nextval,4,100,'길을 잃어야 길을 찾는법을 안다',807);
insert into tblReview values (seqReview.nextval,3,40,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',808);
insert into tblReview values (seqReview.nextval,3,40,'왜 평점이 높은지 모르겠음',809);
insert into tblReview values (seqReview.nextval,4,60,'웨스앤더슨의 동화속에서 살고싶다.',810);
insert into tblReview values (seqReview.nextval,3,20,'이 시리지는 다 봐야겠음.',811);
insert into tblReview values (seqReview.nextval,1,100,'슬픔이 있어야 행복이 존재한다.',812);
insert into tblReview values (seqReview.nextval,4,100,'몰입도 짱짱ㅜㅜ',813);
insert into tblReview values (seqReview.nextval,3,60,'웨스앤더슨의 동화속에서 살고싶다.',814);
insert into tblReview values (seqReview.nextval,4,80,'3번을 보아도 시간가는 줄 몰랐습니다',815);
insert into tblReview values (seqReview.nextval,3,40,'재밌었어요 재미있게 봤습니당',816);
insert into tblReview values (seqReview.nextval,3,80,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',817);
insert into tblReview values (seqReview.nextval,1,100,'저는 약간 지루했네요;;',818);
insert into tblReview values (seqReview.nextval,3,100,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',819);
insert into tblReview values (seqReview.nextval,3,100,'재밌어요',820);
insert into tblReview values (seqReview.nextval,2,60,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',821);
insert into tblReview values (seqReview.nextval,1,40,'길을 잃어야 길을 찾는법을 안다',822);
insert into tblReview values (seqReview.nextval,3,60,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',823);
insert into tblReview values (seqReview.nextval,4,40,'재밌었어요 재미있게 봤습니당',824);
insert into tblReview values (seqReview.nextval,3,60,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',825);
insert into tblReview values (seqReview.nextval,3,40,'This film is dedicated to our kids. Please don’t grow up. Ever',826);
insert into tblReview values (seqReview.nextval,2,20,'재밌어요',827);
insert into tblReview values (seqReview.nextval,1,80,'너무좋았습니다 주옥같은 대사들의 향연',828);
insert into tblReview values (seqReview.nextval,1,80,'This film is dedicated to our kids. Please don’t grow up. Ever',829);
insert into tblReview values (seqReview.nextval,2,40,'위로를 주는 존재와 목소리',830);
insert into tblReview values (seqReview.nextval,3,100,'최근본거중에 레전드ㄷㄷ',831);
insert into tblReview values (seqReview.nextval,3,40,'감정을 억제하기보다 보듬어야 하는 이유.',832);
insert into tblReview values (seqReview.nextval,4,40,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',833);
insert into tblReview values (seqReview.nextval,4,80,'손에 꼽히는 인생캐릭터를 만난 것 같다',834);
insert into tblReview values (seqReview.nextval,2,80,'재밌었어요 재미있게 봤습니당',835);
insert into tblReview values (seqReview.nextval,4,80,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',836);
insert into tblReview values (seqReview.nextval,4,20,'꿀잼',837);
insert into tblReview values (seqReview.nextval,2,40,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',838);
insert into tblReview values (seqReview.nextval,5,40,'별 다섯개를 오색으로 입히고 싶다.',839);
insert into tblReview values (seqReview.nextval,3,40,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',840);
insert into tblReview values (seqReview.nextval,3,20,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',841);
insert into tblReview values (seqReview.nextval,3,20,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',842);
insert into tblReview values (seqReview.nextval,2,40,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',843);
insert into tblReview values (seqReview.nextval,3,20,'슬프거나 기뻐서 운 게 아니라, 지구 반대편 생판 모르는 사람들이 이렇게 나를 들여다보고 토닥여주는 게 고마워서 울었다.',844);
insert into tblReview values (seqReview.nextval,5,40,'This film is dedicated to our kids. Please don’t grow up. Ever',845);
insert into tblReview values (seqReview.nextval,2,80,'보는내내 답답합니다.정말 답답합니다.',846);
insert into tblReview values (seqReview.nextval,4,40,'감정을 억제하기보다 보듬어야 하는 이유.',847);
insert into tblReview values (seqReview.nextval,2,80,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',848);
insert into tblReview values (seqReview.nextval,2,80,'언제 봐도 좋습니다 ~~!^^',849);
insert into tblReview values (seqReview.nextval,1,80,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',850);
insert into tblReview values (seqReview.nextval,5,100,'생각보다 유치했어요',851);
insert into tblReview values (seqReview.nextval,2,40,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',852);
insert into tblReview values (seqReview.nextval,2,20,'모르겠다. 그냥 펑펑 울었다..',853);
insert into tblReview values (seqReview.nextval,3,80,'최근본거중에 레전드ㄷㄷ',854);
insert into tblReview values (seqReview.nextval,3,20,'웨스앤더슨의 동화속에서 살고싶다.',855);
insert into tblReview values (seqReview.nextval,3,20,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',856);
insert into tblReview values (seqReview.nextval,5,40,'언제 봐도 좋습니다 ~~!^^',857);
insert into tblReview values (seqReview.nextval,3,60,'기대이상으로 너무 재밌어요',858);
insert into tblReview values (seqReview.nextval,2,100,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',859);
insert into tblReview values (seqReview.nextval,5,20,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',860);
insert into tblReview values (seqReview.nextval,5,60,'This film is dedicated to our kids. Please don’t grow up. Ever',861);
insert into tblReview values (seqReview.nextval,4,80,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',862);
insert into tblReview values (seqReview.nextval,4,20,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',863);
insert into tblReview values (seqReview.nextval,3,60,'기대이상으로 너무 재밌어요',864);
insert into tblReview values (seqReview.nextval,1,20,'슬픔이 있어야 행복이 존재한다.',865);
insert into tblReview values (seqReview.nextval,5,80,'고전의 힘',866);
insert into tblReview values (seqReview.nextval,5,40,'손에 꼽히는 인생캐릭터를 만난 것 같다',867);
insert into tblReview values (seqReview.nextval,4,20,'개인적으로 완전 만족하면서 봤음 강추bb',868);
insert into tblReview values (seqReview.nextval,3,100,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',869);
insert into tblReview values (seqReview.nextval,2,100,'최근본거중에 레전드ㄷㄷ',870);
insert into tblReview values (seqReview.nextval,4,100,'웨스앤더슨의 동화속에서 살고싶다.',871);
insert into tblReview values (seqReview.nextval,4,100,'왜 평점이 높은지 모르겠음',872);
insert into tblReview values (seqReview.nextval,1,40,'재밌어요',873);
insert into tblReview values (seqReview.nextval,3,40,'기대이상으로 너무 재밌어요',874);
insert into tblReview values (seqReview.nextval,4,100,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',875);
insert into tblReview values (seqReview.nextval,5,80,'개인적으로 완전 만족하면서 봤음 강추bb',876);
insert into tblReview values (seqReview.nextval,5,80,'언제 봐도 좋습니다 ~~!^^',877);
insert into tblReview values (seqReview.nextval,5,40,'This film is dedicated to our kids. Please don’t grow up. Ever',878);
insert into tblReview values (seqReview.nextval,5,80,'생각보다 유치했어요',879);
insert into tblReview values (seqReview.nextval,3,40,'This film is dedicated to our kids. Please don’t grow up. Ever',880);
insert into tblReview values (seqReview.nextval,5,20,'언제 봐도 좋습니다 ~~!^^',881);
insert into tblReview values (seqReview.nextval,1,40,'This film is dedicated to our kids. Please don’t grow up. Ever',882);
insert into tblReview values (seqReview.nextval,3,20,'모르겠다. 그냥 펑펑 울었다..',883);
insert into tblReview values (seqReview.nextval,5,20,'꿀잼',884);
insert into tblReview values (seqReview.nextval,2,100,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',885);
insert into tblReview values (seqReview.nextval,3,40,'보는내내 답답합니다.정말 답답합니다.',886);
insert into tblReview values (seqReview.nextval,5,40,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',887);
insert into tblReview values (seqReview.nextval,5,60,'생각보다 유치했어요',888);
insert into tblReview values (seqReview.nextval,1,60,'이 시리지는 다 봐야겠음.',889);
insert into tblReview values (seqReview.nextval,4,100,'이 시리지는 다 봐야겠음.',890);
insert into tblReview values (seqReview.nextval,4,60,'보는내내 답답합니다.정말 답답합니다.',891);
insert into tblReview values (seqReview.nextval,1,80,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',892);
insert into tblReview values (seqReview.nextval,5,100,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',893);
insert into tblReview values (seqReview.nextval,1,60,'개인적으로 완전 만족하면서 봤음 강추bb',894);
insert into tblReview values (seqReview.nextval,5,20,'길을 잃어야 길을 찾는법을 안다',895);
insert into tblReview values (seqReview.nextval,1,60,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',896);
insert into tblReview values (seqReview.nextval,1,40,'3번을 보아도 시간가는 줄 몰랐습니다',897);
insert into tblReview values (seqReview.nextval,3,100,'이 시리지는 다 봐야겠음.',898);
insert into tblReview values (seqReview.nextval,2,60,'길을 잃어야 길을 찾는법을 안다',899);
insert into tblReview values (seqReview.nextval,4,20,'This film is dedicated to our kids. Please don’t grow up. Ever',900);
insert into tblReview values (seqReview.nextval,4,100,'고전의 힘',901);
insert into tblReview values (seqReview.nextval,1,100,'사랑하는 사람과 함께라면 어디든 낙원이다.',902);
insert into tblReview values (seqReview.nextval,3,100,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',903);
insert into tblReview values (seqReview.nextval,1,60,'기대이상으로 너무 재밌어요',904);
insert into tblReview values (seqReview.nextval,5,80,'모르겠다. 그냥 펑펑 울었다..',905);
insert into tblReview values (seqReview.nextval,3,80,'한 소년과 한 소녀 그리고 그들만의 판타지',906);
insert into tblReview values (seqReview.nextval,3,80,'동화같은화면 동화같은이야기',907);
insert into tblReview values (seqReview.nextval,5,60,'동심으로 떠나는 여행...? 좀 부족하다...',908);
insert into tblReview values (seqReview.nextval,1,40,'이 시리지는 다 봐야겠음.',909);
insert into tblReview values (seqReview.nextval,2,100,'사랑하는 사람과 함께라면 어디든 낙원이다.',910);
insert into tblReview values (seqReview.nextval,5,40,'모르겠다. 그냥 펑펑 울었다..',911);
insert into tblReview values (seqReview.nextval,2,40,'재밌어요',912);
insert into tblReview values (seqReview.nextval,5,40,'몰입도 짱짱ㅜㅜ',913);
insert into tblReview values (seqReview.nextval,3,100,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',914);
insert into tblReview values (seqReview.nextval,4,40,'언제 봐도 좋습니다 ~~!^^',915);
insert into tblReview values (seqReview.nextval,3,60,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',916);
insert into tblReview values (seqReview.nextval,3,60,'기대이상으로 너무 재밌어요',917);
insert into tblReview values (seqReview.nextval,4,40,'위로를 주는 존재와 목소리',918);
insert into tblReview values (seqReview.nextval,5,80,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',919);
insert into tblReview values (seqReview.nextval,3,80,'동화같은화면 동화같은이야기',920);
insert into tblReview values (seqReview.nextval,4,80,'동심으로 떠나는 여행...? 좀 부족하다...',921);
insert into tblReview values (seqReview.nextval,2,80,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',922);
insert into tblReview values (seqReview.nextval,2,60,'재밌었어요 재미있게 봤습니당',923);
insert into tblReview values (seqReview.nextval,1,100,'한 소년과 한 소녀 그리고 그들만의 판타지',924);
insert into tblReview values (seqReview.nextval,3,20,'모르겠다. 그냥 펑펑 울었다..',925);
insert into tblReview values (seqReview.nextval,3,80,'사랑하는 사람과 함께라면 어디든 낙원이다.',926);
insert into tblReview values (seqReview.nextval,1,40,'생각보다 유치했어요',927);
insert into tblReview values (seqReview.nextval,5,40,'감동적입니다.',928);
insert into tblReview values (seqReview.nextval,3,60,'사랑하는 사람과 함께라면 어디든 낙원이다.',929);
insert into tblReview values (seqReview.nextval,1,80,'언제 봐도 좋습니다 ~~!^^',930);
insert into tblReview values (seqReview.nextval,5,60,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',931);
insert into tblReview values (seqReview.nextval,4,60,'생각보다 유치했어요',932);
insert into tblReview values (seqReview.nextval,4,20,'왜 평점이 높은지 모르겠음',933);
insert into tblReview values (seqReview.nextval,2,80,'슬픔이 있어야 행복이 존재한다.',934);
insert into tblReview values (seqReview.nextval,3,20,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',935);
insert into tblReview values (seqReview.nextval,2,100,'꿀잼',936);
insert into tblReview values (seqReview.nextval,1,20,'동심으로 떠나는 여행...? 좀 부족하다...',937);
insert into tblReview values (seqReview.nextval,2,20,'청춘이란 이유로 용기낼 수 있는 해가 뜨기 전 하룻밤까지만',938);
insert into tblReview values (seqReview.nextval,3,60,'이 시리지는 다 봐야겠음.',939);
insert into tblReview values (seqReview.nextval,1,20,'최근본거중에 레전드ㄷㄷ',940);
insert into tblReview values (seqReview.nextval,1,20,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',941);
insert into tblReview values (seqReview.nextval,1,40,'꿀잼',942);
insert into tblReview values (seqReview.nextval,5,80,'생각보다 유치했어요',943);
insert into tblReview values (seqReview.nextval,1,80,'셰익스피어 작품을 지금도 봐야할 이유가 되어주는 작품',944);
insert into tblReview values (seqReview.nextval,4,40,'언제 봐도 좋습니다 ~~!^^',945);
insert into tblReview values (seqReview.nextval,3,80,'꿀잼',946);
insert into tblReview values (seqReview.nextval,3,100,'모르겠다. 그냥 펑펑 울었다..',947);
insert into tblReview values (seqReview.nextval,5,20,'상당히 기대를 많이 했는데 그 기대치에는 못 미쳤던 같네요 ㅠㅠ',948);
insert into tblReview values (seqReview.nextval,1,80,'최근본거중에 레전드ㄷㄷ',949);
insert into tblReview values (seqReview.nextval,2,80,'길을 잃어야 길을 찾는법을 안다',950);
insert into tblReview values (seqReview.nextval,2,80,'한 소년과 한 소녀 그리고 그들만의 판타지',951);
insert into tblReview values (seqReview.nextval,3,80,'This film is dedicated to our kids. Please don’t grow up. Ever',952);
insert into tblReview values (seqReview.nextval,5,80,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',953);
insert into tblReview values (seqReview.nextval,3,40,'감동적입니다.',954);
insert into tblReview values (seqReview.nextval,3,60,'위로를 주는 존재와 목소리',955);
insert into tblReview values (seqReview.nextval,5,60,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',956);
insert into tblReview values (seqReview.nextval,1,40,'스토리 자체는 좋았지만 솔직히 재미 부분은 떨어졌습니다',957);
insert into tblReview values (seqReview.nextval,2,20,'감정을 억제하기보다 보듬어야 하는 이유.',958);
insert into tblReview values (seqReview.nextval,1,40,'동화같은화면 동화같은이야기',959);
insert into tblReview values (seqReview.nextval,1,80,'고전의 힘',960);
insert into tblReview values (seqReview.nextval,4,20,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',961);
insert into tblReview values (seqReview.nextval,4,20,'길을 잃어야 길을 찾는법을 안다',962);
insert into tblReview values (seqReview.nextval,2,80,'여행지에서 사랑에 빠진 이들의 달콤한 대화를 엿듣는 기분으로.',963);
insert into tblReview values (seqReview.nextval,2,60,'저는 약간 지루했네요;;',964);
insert into tblReview values (seqReview.nextval,5,80,'한 소년과 한 소녀 그리고 그들만의 판타지',965);
insert into tblReview values (seqReview.nextval,5,60,'최근본거중에 레전드ㄷㄷ',966);
insert into tblReview values (seqReview.nextval,2,60,'3번을 보아도 시간가는 줄 몰랐습니다',967);
insert into tblReview values (seqReview.nextval,5,80,'3번을 보아도 시간가는 줄 몰랐습니다',968);
insert into tblReview values (seqReview.nextval,5,20,'재밌었어요 재미있게 봤습니당',969);
insert into tblReview values (seqReview.nextval,3,100,'위로를 주는 존재와 목소리',970);
insert into tblReview values (seqReview.nextval,4,40,'재밌어요',971);
insert into tblReview values (seqReview.nextval,1,40,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',972);
insert into tblReview values (seqReview.nextval,3,20,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',973);
insert into tblReview values (seqReview.nextval,4,100,'너무좋았습니다 주옥같은 대사들의 향연',974);
insert into tblReview values (seqReview.nextval,3,100,'꿀잼',975);
insert into tblReview values (seqReview.nextval,1,100,'재미있다. 아름답다. 예쁘다.',976);
insert into tblReview values (seqReview.nextval,4,40,'몰입도 짱짱ㅜㅜ',977);
insert into tblReview values (seqReview.nextval,5,60,'슬픔이 있어야 행복이 존재한다.',978);
insert into tblReview values (seqReview.nextval,1,80,'청춘이란 이유로 용기낼 수 있는 해가 뜨기 전 하룻밤까지만',979);
insert into tblReview values (seqReview.nextval,5,80,'감동적입니다.',980);
insert into tblReview values (seqReview.nextval,1,100,'놀라웠다, 야영에 불필요한것들만 잔뜩 가져온 그녀를 이해하는 그. 가감이없다',981);
insert into tblReview values (seqReview.nextval,3,40,'재밌어요',982);
insert into tblReview values (seqReview.nextval,5,20,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',983);
insert into tblReview values (seqReview.nextval,5,80,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',984);
insert into tblReview values (seqReview.nextval,5,60,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',985);
insert into tblReview values (seqReview.nextval,2,80,'몰입도 짱짱ㅜㅜ',986);
insert into tblReview values (seqReview.nextval,2,40,'많은 평론가들이 극찬하지만, 개인적으로 그정도는 아니였다',987);
insert into tblReview values (seqReview.nextval,3,40,'웨스앤더슨의 동화속에서 살고싶다.',988);
insert into tblReview values (seqReview.nextval,5,60,'모든 게 귀엽고 아름답다. 슬며시 입가에 웃음이 떠오른다.',989);
insert into tblReview values (seqReview.nextval,4,40,'개인적으로 완전 만족하면서 봤음 강추bb',990);
insert into tblReview values (seqReview.nextval,2,60,'나의 어렸을적 상상의 친구는 누구였을까 .. 빙봉ㅜㅜ',991);
insert into tblReview values (seqReview.nextval,2,40,'감정을 억제하기보다 보듬어야 하는 이유.',992);
insert into tblReview values (seqReview.nextval,5,20,'슬픔은 참 역설적이다. 슬퍼야만 슬픔을 극복할 수 있다는 것이.',993);
insert into tblReview values (seqReview.nextval,1,80,'사랑하는 사람과 함께라면 어디든 낙원이다.',994);
insert into tblReview values (seqReview.nextval,3,20,'너무좋았습니다 주옥같은 대사들의 향연',995);
insert into tblReview values (seqReview.nextval,5,60,'고전의 힘',996);
insert into tblReview values (seqReview.nextval,4,80,'우리는 성숙 이라는 단어로 얼마나 많은 슬픔이들을 가둬왔을까',997);
insert into tblReview values (seqReview.nextval,3,60,'동심으로 떠나는 여행...? 좀 부족하다...',998);
insert into tblReview values (seqReview.nextval,3,80,'감동적입니다.',999);
insert into tblReview values (seqReview.nextval,4,80,'이 시리지는 다 봐야겠음.',1000);
